### ISSUE TITLE
Running some code once per set of examples

### ISSUE THREAD

**Issue by bapti** [adamralph/xbehave.net#145]
I am using xBehave to test my webserver actions.  Is it possible to get it to only login once?  At the moment it runs the login step before each example.  I guess I could override with a static or something but just wondering if there's built in functionality for this kind of behaviour.

``` C#
[Background]
public void Background()
{
    "Given a logged in user"
        .Given(() => 
        {
            bool result = Login();
            result.Should().BeTrue();
        });
}

[Scenario]
[Example("/")]
[Example("/dashboard")]
public void SmokeTest(string route, HttpResponseMessage response)
{
    "When I request the url"
        .When(() => {
            response = Get(route);
        });

    "Then I expect a 200 response"
        .Then(() => {
            response.StatusCode.Should().Be(HttpStatusCode.OK);
        });
}
```

**Comment by adamralph** [comment]
Hi @bapti, there's no specific feature built for this, but if you replace your background method with a constructor for your test class then that should do the trick. IIRC an instance of your test class will be constructed once per test run so the constructor will only be executed once.

(Note that if you find you also need to do some disposal/teardown after your scenarios have been executed then you can use xunit.net's `IUseFixture` feature instead but currently you have to jump through a small hoop to get that working in xBehave.net - see https://github.com/xbehave/xbehave.net/wiki/Can%27t-access-fixture-data-when-using-IUseFixture.)

For the future, it could be interesting to introduce the concept of 'scope' to background methods to make things more obvious, e.g.

``` C#
[Background(BackgroundScope.Scenario)] // default, matching the behaviour of Cucumber
[Background(BackgroundScope.Class)]
[Background(BackgroundScope.Assembly)]
```

**Comment by adamralph** [comment]
Ah, sorry, I should read things more carefully. You want to run your background _per set of examples_. Well, I don't think there's a way of achieving exactly that right now. Perhaps for now you can muddle through things using class constructors or `IUseFixture` and by splitting up your scenarios across classes appropriately.

So I guess my background scope proposal would have to be:

``` C#
[Background(BackgroundScope.Example)] // default, matching the behaviour of Cucumber
[Background(BackgroundScope.Scenario)] // what you need right now
[Background(BackgroundScope.Class)]
[Background(BackgroundScope.Assembly)]
```

**Comment by adamralph** [comment]
@bapti what do you think of my feature proposal? Would you find it useful?

**Comment by adamralph** [comment]
Another way to do this is to introduce a new attribute that runs before and after each 'scenario outline' which, in Gherkin, means 'the set of all scenarios generated from the examples'. E.g.

``` C#
[Scenario]
[Login]
[Example("/")]
[Example("/dashboard")]
public void SmokeTest(string route, HttpResponseMessage response)
{
    "When I request the url"
        .When(() => {
            response = Get(route);
        });

    "Then I expect a 200 response"
        .Then(() => {
            response.StatusCode.Should().Be(HttpStatusCode.OK);
        });
}

public class LoginAttribute : BeforeAfterScenarioOutlineAttribute
{
    public override void Before()
    {
        Login().Should().BeTrue();
    }
}
```

**Comment by adamralph** [comment]
I'm going to proceed with this using the attribute based design, unless anyone voices an opinion.

**Comment by adamralph** [comment]
@bapti I'm going to close this because right now I can't see a compelling reason to have a facility to run something once per set of examples, as opposed to running once for the entire test class (which can be achieved using either a constructor or xunit's `IClassFixture` (`IUseFixture` in xunit 1.x).
