### ISSUE TITLE
Add equivalent of Gherkin Feature

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#18]
See https://github.com/cucumber/cucumber/wiki/Feature-Introduction
# Ideas

```
[Feature("Captcha")]                                         // no distinction of name
[Feature("In order to stop bots from spamming the site")]    // repetition of attribute
[Feature("As a member of the commercial team")]
[Feature("I want users to fill in a captcha")]
public static class CaptchaFeature
{
}

[Feature(
    "Captcha",                                       
    "In order to stop bots from spamming the site",    // no distinction of name
    "As a member of the commercial team",
    "I want users to fill in a captcha")]              // ugly layout?
public static class CaptchaFeature
{
}

[Feature("Captcha")]                               
[InOrderTo("stop bots from spamming the site")]    // too restrictive? (the language is still evolving)
[AsA("member of the commercial team")]             // these are not gherkin keywords (all other attributes are equivalent to a gherkin keyword)
[IWant("users to fill in a captcha")]
public static class CaptchaFeature
{
}
```

**Comment by adamralph** [comment]
The only use of this would be for test runner output, but I'm still not sure how exactly it could be done. May only be something useable by a custom test runner.

May be able to use Xunit.RunWithAttribute as a base class for FeatureAttribute, pointing to an ITestClassCommand derived type which puts the feature info into test-suite name in the XML/HTML output.

**Comment by domgreen** [comment]
Would like this added would give us the ability to use it as a setup / tear down of many scenarios like IUseFixture in xUnit.
Would allow me to do something like build my db before all tests are run then delete it after all tests / scenarios are run therefore doing it once for a number of scenarios.

**Comment by adamralph** [comment]
This isn't the feature you're looking for :wink:. This is just about adding some extra metadata to the test output.

Have you tried using xUnit.net's IUseFixture with xBehave.net? I think it may _just work_. The execution of xBehave.net scenarios is designed to follow the mechanisms of standard xUnit tests as closely as possible so a lot of the stuff you can do with xUnit.net should work in the same way with xBehave.net. I'd be interested to know if it works for you (I've never tried).

**Comment by domgreen** [comment]
It kinda works ... using IUseFixture I can create my db using the features ctor and destroy it using Dispose but the data that I set in SetFixture(MyFixture fxture) seems to get clear down inside each xBehave step, will dig into it today and see if I'm doing anything crazy.

**Comment by adamralph** [comment]
Aha - now I remember. There is an issue with IUseFixture, the details are at https://github.com/xbehave/xbehave.net/issues/87.

Until the issue is addressed properly, the (slightly ugly) workaround is to make the field which holds your fixture data `static`.

**Comment by domgreen** [comment]
Yeah that's exactly what I've done for the moment ... will keep am eye on that bug. :) thanks.

**Comment by adamralph** [comment]
Great - in the meantime I've added it to a new 'known issues' page on the wiki - https://github.com/xbehave/xbehave.net/wiki/Known-Issues

**Comment by adamralph** [comment]
Doesn't seem to be enough ROI on this.
