### ISSUE TITLE
Introduce a BeforeAfterScenarioAttribute

### ISSUE THREAD

**Issue by georgehemmings** [adamralph/xbehave.net#186]
I think it would be useful if there was a BeforeAfterScenarioAttribute available for extensions. This would be like xUnit's BeforeAfterTestAttribute, and would allow cross-cutting set-up for acceptance tests, like starting servers, and restoring databases.

**Comment by adamralph** [comment]
That's an interesting idea. I'm not familiar with the BeforeAfter attribute
so I'll get up to speed on that and then report back.

**Comment by adamralph** [comment]
is BeforeAfterTestAttribute an xUnit 2.0 only feature?

**Comment by adamralph** [comment]
Ignore me, I've found it in 1.9.2.

**Comment by adamralph** [comment]
OK, so I can see that in xBehave.net 1.x, xUnit.net's `BeforeAfterTestAttribute` will be invoked before and after each step. I guess that may have some use, but I can see that something that runs before and after each scenario would be better.

In fact, you can achieve this right now using `Background`. Your 'before' is the content of the background steps, and your 'after' is whatever you put in the teardowns. E.g.

``` C#
[Background]
public void Background()
{
    "Given ..."
        .f(() => ...) // before
        .Teardown(() => ...); // after
}

[Scenario]
public void Something()
{
    ...
}
```

Would that satisfy your needs?

**Comment by georgehemmings** [comment]
This will work. Although this would report the step in the output. I'd end up with something like "Given there is a database". Cucumber has hooks for `before`, `after`, and `around` scenario actions to set-up the common infrastructure. (https://github.com/DatabaseCleaner/database_cleaner#cucumber-example)

Pushing these concerns into attributes keeps the scenarios focused. I'll use a `Feature` base class for now.

**Comment by georgehemmings** [comment]
It looks like SpecFlow has some attributes to support hooks https://github.com/techtalk/SpecFlow/wiki/Hooks

**Comment by adamralph** [comment]
Interesting. Yes, I can see the value in having stuff that doesn't appear in the test output. I guess ideally we'd want `BeforeAfterStep` (synonym for `Xunit.BeforeAfterTest`), `BeforeAfterScenario` and `BeforeAfterFeature` (currently no way to achieve this effect in xBehave.net). With xUnit 2.0 it may be even be possible to have a `BeforeAfterFeatures` for the entire assembly.

Either way, this will be a 2.0 or later feature. 1.x is in critical bug-fix only mode. Unless of course it gets submitted as a contribution :wink:.

**Comment by georgehemmings** [comment]
`BeforeAfterFeatures` would be a great addition, particularly for acceptance/system testing. There isn't a clean way of doing this in xUnit currently.

**Comment by adamralph** [comment]
Agreed. At the moment, at work, we do all our before/after at that level in our build script, which is fine when running the build script, but for debugging in VS, it means manual steps to get things working.

**Comment by adamralph** [comment]
@georgehemmings the behaviour of `BeforeAfterTestAttribute` has changed in xBehave 2.0 (currently in beta) and it will exhibit the exact behaviour that you are proposing for the `BeforeAfterScenarioAttribute`. I.e. it will be run before and after the scenario, rather than each step.

I'll leave this issue open since it may still be worth introducing a `BeforeAfterScenarioAttribute`, purely as a synonym of `BeforeAfterTestAttribute`, just to convey the semantics a little better.

**Comment by georgehemmings** [comment]
Hi @adamralph

Is `BeforeAfterFeatures` possible yet?

**Comment by adamralph** [comment]
@georgehemmings I'm afraid not.

Perhaps the solution is to use xunit 2.0's [Collection Fixtures](https://xunit.github.io/docs/shared-context.html#collection-fixture) feature. This should work seamlessly with classes containing xbehave scenarios.

**Comment by georgehemmings** [comment]
Thanks, I will look into collections.
