### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#223]

**Comment by lhaussknecht** [comment]
What do you like to see here? Best practice seems to me to factor out all of your business logic into a pcl project, which can be easily tested.

**Comment by adamralph** [comment]
@lhaussknecht the idea here was to provide support for the Xamarin TFN's to match those supported in xunit 2.x. Currently, in xunit 2.1, those are provided by a single "dotnet" DLL which happens to be a Profile259 PCL project.

However, all of this is set to change with .NET Core so I don't think it's worth investing any time in this. I also think that, ultimately, support for the Xamarin platforms will be provided via support for the relevant [.NET Standard](https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7), so I don't think explicit Xamarin support will ever be a thing in xBehave.net. For that reason, I'm going to close this issue.

The approach you mention of factoring as much as possible into a PCL, and testing that, is a sound approach and will take care of most testing requirements in the meantime. However, end platform support (e.g. devices) in testing frameworks like xbehave can be useful, should application developers want to use those frameworks to perform some testing at the device level (e.g. UI testing).
