### ISSUE TITLE
DNX/CoreCLR/dotnet/netstandard platform support

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#224]
For use by non-desktop runners, e.g. DNX.

Requires linking to xunit 2.1.

---

_update_
On hold, pending _whatever it is called_ RC2 (plus the corresponding future xunit release).

**Comment by DerAlbertCom** [comment]
Any plans to support .net core?

**Comment by adamralph** [comment]
Hi Albert. This is planned for the 2.1 release. This will be linked to
xunit 2.1 (currently in beta), which also introduces .net core support.

**Comment by mvalipour** [comment]
@adamralph is there any nuget distribution of betas for 2.1? I'm specially interested in the dnx support.

**Comment by adamralph** [comment]
@mvalipour none yet I'm afraid. It seems to be a popular theme so I'm marking this as a top priority.

**Comment by mvalipour** [comment]
@adamralph 

OK, I managed to build a dnx package and get xbehave to run successfully on it!

The code is on a repo here (for now)
https://github.com/mvalipour/xbehave.dnx.test

99.9% of the code is same as the `desktop` execution, but I have copied them across for now.  
if you are happy with this, we could discuss merging this into the main repo.

![](http://i.imgur.com/86AocgD.png)

**Comment by adamralph** [comment]
@mvalipour it's great that you got it working!

Would you like to send a pull request?

**Comment by kirk-marple** [comment]
@mvalipour I'd like to play around with your DNX version of Xbehave.  

Is your repo replacing the 'Xbehave' dependency in a typical DNX project? 

Is the 'ScenarioX' attribute required to make this work?

I have several DNX projects using beta7, and already linking with xunit 2.1, and had been using xunit.runner.dnx.  Just wasn't sure what I'd need to change to try out your test build?

**Comment by mvalipour** [comment]
@kirk-marple I'm preparing a PR to be hopefully be merged into xbehave, however you are welcome to use my unofficial version for now.

There is a test project in my repo which contains the calculator example. And yes, that attribute has been added on my repo to hack around, however would change on the finished version.

https://github.com/mvalipour/xbehave.dnx.test/tree/master/src/XBehave.test.dnx

**Comment by kirk-marple** [comment]
@mvalipour Thanks, if this is being worked on, I'll wait for the beta of xbehave, I guess.  I'd prefer not to use the hacked attribute for now.

@adamralph Adam, is there any ETA on when you may have a beta ready?  We really want to move to Xbehave ASAP, but are using DNX projects.  I have some tests built, but no way to run them yet :)

**Comment by adamralph** [comment]
@kirk-marple it depends how soon @mvalipour can send the PR :smile:

**Comment by mvalipour** [comment]
#### Update

I have pulled-together dnx projects [which can be found here](https://github.com/mvalipour/xbehave.net/tree/feature/support-dnx/src/dnx). However there are some issues I'm having trouble with which maybe not be fixed until next week (I'm unavailable for a week).

Specifically the issue is around the fact that xunit picks up `dotnet` execution and hits [this not-supported-exception](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Reflection/ReflectionMethodInfo.cs#L71) which is invoked by [this part of xbehave](https://github.com/mvalipour/xbehave.net/blob/feature/support-dnx/src/Xbehave.2.Execution.desktop/ScenarioInvoker.cs#L183).

In case you guys wanted to try it out, I have pushed these temporary packages to my myget feed at:

https://www.myget.org/F/mvalipour/

**Comment by mvalipour** [comment]
PR: #279

**Comment by mvalipour** [comment]
@adamralph It's been a while since the PR, do you have any plans for merging?

**Comment by adamralph** [comment]
@mvalipour I had a brief look but I haven't had time to look in detail. The addition of dotnet TFN support is quite a major change and I don't really know exactly how things should look without spending a lot more time on it. Your PR is hugely appreciated, please don't take the delay in merging as a lack of appreciation. I'm hoping to get enough time in December to not only merge your PR but also push out the  stable package to NuGet.

**Comment by mvalipour** [comment]
@adamralph not at all, I would look forward for that to happen.

**Comment by adamralph** [comment]
for reference: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

**Comment by adamralph** [comment]
Putting this on hold for now.

There's just too much churn coming in RC2 to spend any time on this now. Most of the effort would probably be wasted.

**Comment by adamralph** [comment]
This is all set to change with .NET Core so I don't think it's worth investing any time in this. I also think that, ultimately, support for all platforms will be provided via support for the relevant [.NET Standard](https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7), so I don't think explicit support for anything other than net45 will ever be a thing in xBehave.net. For that reason, I'm going to close this issue.

**Comment by adamralph** [comment]
Replaced by #300
