### ISSUE TITLE
Switch to 'standard' .net layout

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#236]
https://gist.github.com/davidfowl/ed7564297c61fe9ab814

**Comment by ursenzler** [comment]
I wouldn't work against what Visual Studio thinks how the world is, even if it would be conceptually better.
-> .sln inside \src
-> tests and production code both on same level (as projects in VS)

**Comment by adamralph** [comment]
It just needs some solution folder magic dust sprinkled in :sparkles:
