### ISSUE TITLE
Steps which follow a failed a step are skipped

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#245]
In 1.x, they are failed.

**Comment by KristyJGuo** [comment]
Hi, this issue have been fixed?

**Comment by adamralph** [comment]
@KristyJGuo it's in the 2.0 release candidate, which is available at https://www.nuget.org/packages/Xbehave/2.0.0-rc003-build581

This feature will not be added to 1.x.

**Comment by KristyJGuo** [comment]
@adamralph , Really thanks, I installed the package, but I don't know how to use it. Do you have some information/wiki page about it?

**Comment by KristyJGuo** [comment]
Hi @adamralph ,
Sorry, I misunderstood your title. In my case, I want to continue to execute steps which follow a failed step, not skipped. Do you have some ideas?

**Comment by adamralph** [comment]
@KristyJGuo ah, I see. Sure, you can do this in 1.x with an undocumented feature:

``` C#
[ContinueOnFailureAfter(StepType.Then)]
```

This is effectively saying:

> After the first step beginning with "Then " has executed, continue to execute all steps, even if a step fails.

You can add this attribute to a method, a class, or even an entire assembly:

``` C#
[assembly: ContinueOnFailureAfter(StepType.Then)]
```

This attribute was removed in 2.x since it was rarely used and added considerable implementation overhead, but you can replicate the same behaviour using your own custom step definition filter attribute. See https://github.com/xbehave/xbehave.net/issues/254

**Comment by KristyJGuo** [comment]
Hi @adamralph 
I installed 1.0, 

```
[Binding]
[ContinueOnFailureAfter(StepType.Any)]
public class SpecFlowFeature1Steps
{

    [Given(@"I have entered (.*) into the calculator")]
    public void GivenIHaveEnteredIntoTheCalculator(int p0)
    {
        Assert.Equal("b", "a");

    }

    [When(@"I press add")]
    public void WhenIPressAdd()
    {
        Assert.Equal("b", "b");
    }

    [Then(@"the result should be (.*) on the screen")]
    public void ThenTheResultShouldBeOnTheScreen(int p0)
    {
        Assert.Equal("b", "b");
    }
}
```

But after the Given step failed, the When and Then steps still Skipped. What's wrong with it?

**Comment by adamralph** [comment]
@KristyJGuo that example is from SpecFlow, not xBehave.net.

**Comment by adamralph** [comment]
https://www.nuget.org/packages/Xbehave/2.0.0

https://github.com/xbehave/xbehave.net/releases/tag/2.0.0
