### ISSUE TITLE
uninitialized constant XUnitTestRunner

### ISSUE THREAD

**Issue by ursenzler** [adamralph/xbehave.net#248]
Clean clone of the dev branch

installed ruby (at least as far I can tell) according to how_to_build.md (except that I downgraded albacore to 1.0)

run rake

aborts with the error message:
`uninitialized constant XUnitTestRunner`

**Comment by adamralph** [comment]
Yeah, this is frustrating. Rubygems is effectively a GAC :cry: I want to convert to Bau ASAP.

Does it work with this?

```
gem install bundler
bundle exec rake
```

**Comment by adamralph** [comment]
Actually there should be a `bundle install` in there too:

```
gem install bundler
bundle install
bundle exec rake
```

If that works for you then we can update the instructions accordingly.

**Comment by adamralph** [comment]
@ursenzler please refer to the new instructions - https://github.com/xbehave/xbehave.net/blob/dev/how_to_build.md
