### ISSUE TITLE
NCrunch Number of Tests

### ISSUE THREAD

**Issue by mvalipour** [adamralph/xbehave.net#269]
So this is not necessarily an issue but a confusion that puzzled me for a bit.

Given NCrunch Separates out the discovery and execution of tests ([see here](http://forum.ncrunch.net/yaf_postst1639_Test-Names--and-so-the-tests--of-xBehave-not-displayed-in-NCrunch-Tests-Windows.aspx#forum_ctl03_MessageList_ctl01_DisplayPostAlt_NameCell)), it does not show correct number tests and also does not respect scenario assertions separately.

![image](https://cloud.githubusercontent.com/assets/2564173/9981370/158ca294-5fb3-11e5-8065-246e5add9892.png)

I'm assuming this is not something that needs fixing on XBehave side, however maybe adding some info here would prevent any confusion.

https://github.com/xbehave/xbehave.net/wiki/Can-I-use-xBehave.net-with-continuous-test-tools%3F

**Comment by adamralph** [comment]
Hi @mvalipour, thanks for raising this.

As you describe, NCrunch isn't able to do any better than this and I agree, we should add something to the docs as you describe. Would you like to have a crack at it? The wiki should be freely editable.

BTW - thanks for the link to the thread in the NCrunch forums, that's very interesting.

**Comment by mvalipour** [comment]
Done:

https://github.com/xbehave/xbehave.net/wiki/Can-I-use-xBehave.net-with-continuous-test-tools%3F#ncrunch

**Comment by adamralph** [comment]
Thank you so much!

**Comment by mvalipour** [comment]
(Y)

BTW, I would be glad to contribute to xBehave, specially around dnx if I could be any help.

**Comment by adamralph** [comment]
@mvalipour your contributions would be more than welcome!
