### ISSUE TITLE
A step expression which assigns a non-completed task results in a hanging test

### ISSUE THREAD

**Issue by chrisalexander** [adamralph/xbehave.net#283]
Hello everyone

I just wrote a few basic xBehave tests under .NET 4.6 for the first time and noted that my tests were behaving unexpectedly. I am using the Visual Studio runner and I observed that the tests were all running to completion, but the test run was not actually completing. In the Test Explorer I had a "cancel" button and code coverage was not run, etc.

I think I have narrowed this down to the following case. Obviously you would never write a test like this in real life but it behaves in the same way that the one I was writing did. I have put the whole thing in a Gist as it is a bit long: https://gist.github.com/chrisalexander/d4c4f93df05e9c0fd264

There is a change in .NET 4.6 where arrow lambdas return the result of the expression ([see here](http://www.kunal-chowdhury.com/2014/12/csharp-6-expression-bodied-method.html))

When you write a test statement that looks like this:

```
"And given a task from that completion source"
    ._(() => task = tcs.Task);
```

(where `tcs` is a `TaskCompletionSource<T>` and  the purpose of the "given" is to assign a task in the method arguments) then you get the correct assignment, but the new language feature means it calls xBehave's `_(Action<Task> body)` method rather than `_(Action body)`, which results in xBehave waiting for the task to complete rather than actually continuing which is what we would expect.

The current workaround I have is to rephrase the test statement thus:

```
"And given a task from that completion source"
    ._(() =>
    {
        task = tcs.Task;
    });
```

This triggers the correct behaviour.

It should be said this isn't really the fault of xBehave, and I'm not even sure there is anything you can really do about it, but I thought it might be worth mentioning as it may confuse some people and it may  raise some questions for you, so I thought it would be worth mentioning. Given part of the point of the library is to help write tests that read nicely, this may cause a stumbling block for some people (especially when I think this test would have worked without hanging in 4.5).

**Comment by adamralph** [comment]
@chrisalexander thanks for raising this! I'm rather swamped right now but I'll take the time to digest this ASAP.

**Comment by chrisalexander** [comment]
@adamralph No problem, I just thought it might be worth at least documenting it somewhere, so that if someone else sees this behaviour they at least have a workaround. As I said I'm not all that sure if there is much Xbehave can do about it, but then there may be something you can think of. Cheers!

**Comment by adamralph** [comment]
hi @chrisalexander, I see what you mean. I ran your gist and observed the same results.

xUnit.net itself suffers from an equivalent problem:

``` C#
[Fact]
public static Task Scenario()
{
    return new TaskCompletionSource<object>().Task;
}
```

but of course, this would be a bizarre thing to write, whereas the case you demonstrate with an xBehave.net step is a very natural thing to write.

Right now, I can't think of any way to prevent this, nor to guide people away from it via the API. The only thing I can think of is to document it in the wiki, and hope that the case of writing a step expression which assigns an uncompleted task is quite rare.

What do you think?

**Comment by chrisalexander** [comment]
@adamralph Thanks for taking a look, good to confirm I'm not going crazy :-)

I suspected that some kind of docs (obviously searchable) would be the likely outcome; the only other thoughts being a somewhat contrived and convoluted combination of waiting for all tests to run except ones which returned tasks and logging a warning to the user that this may have happened, but this could provide false positives and would rely on global state etc, so I would be surprised if it wasn't a complete pain to implement.

Happy for my sample code and notes above to be lifted in to a wiki page if that helps get it started, then maybe just a link back here and it can be closed?

**Comment by jaredpar** [comment]
> There is a change in .NET 4.6 where arrow lambdas return the result of the expression (see here)

This feature is expression bodied members and only affects member declarations: most notably property and method bodies.  It allows the body to be simplified from a braces and a return statement to a single expression.  For example:

``` csharp
// Old
int Prop { get { return 42; } } 
// New
int Prop => 42;
```

The code called out in the gist though is more of this form

``` csharp
"And given a task from that completion source"
    ._(() => task = tcs.Task);
```

That is a expression statement which appears to be calling an extension method on `string` that takes a lambda parameter.  Not completely familiar with this framework so could be wrong here.  

Either way though this is not a use of expression bodied members.  It is the same lambda behavior that has been around since C# 3.0.

**Comment by adamralph** [comment]
@jaredpar thanks for chiming in. So it seems that the reference to .net 4.6 is a red herring. This has been a problem ever since the introduction of async steps to xbehave. I'd like to test and verify this but it's not so easy to lay my hands on a pre-.net 4.6 machine. Anyway, I believe you :wink:. In retrospect it would be quite an odd thing if this wasn't the behaviour since the introduction of expressions.

Still, the fact remains that we need to document this to avoid people tripping up on it. I still don't see any way to guide the user away from it via the API.

**Comment by adamralph** [comment]
Shooting in the dark here, but I'm wondering if there is a way to see if the expression was marked with `async`. In the naive assumption that we'd only want to await step expressions which are marked with `async`, this could be a solution.

**Comment by jaredpar** [comment]
There is no supported way.  It's likely if you dug into a delegate object you could infer that `async` was used at the creation site using some heuristics.  But those are subject to, and often do, change.

**Comment by adamralph** [comment]
Thanks for chiming in. I guess adding some docs is the only way then.

**Comment by adamralph** [comment]
@danielmarbach thanks for chiming on Twitter, much appreciated!

**Comment by adamralph** [comment]
For reference: https://twitter.com/adamralph/status/685896132183068672

**Comment by adamralph** [comment]
Added to [known issues](https://github.com/xbehave/xbehave.net/wiki/Known-Issues), with the workaround.

Thanks @chrisalexander for raising this and @jaredpar for chiming in!
