### ISSUE TITLE
AutoFixture AutoData and Scenario with Example attribute cause double test run

### ISSUE THREAD

**Issue by iamkoch** [adamralph/xbehave.net#285]
Not sure if anyone else has experienced this or even whether this is the right repository, but hoping for some feedback on both.

I have a custom AutoData attribute on my Scenario that gives me composed instances of my core domain. I also wish to use the Example attribute to save duplicating tests, meaning I have a test that looks like this

``` c#
[Scenario]
[DomainAutoData]
[Example("a")]
public void GivenAnInvalidSearchTerm(string invalidTerm...
```

but experience two tests running, one with the correct data from the Example attribute and the other with the value from AutoFixture in the form of "invalidTermdf7sfd7f-f483-sdjfh". Given that the tests are triggered solely by XBehave it feels as though the issue likes somewhere in this repository, and a bit of guidance as to where to focus on would be helpful in order for me to get a PR prepared and raised.

Cheers
Ant

**Comment by adamralph** [comment]
hi @iamkoch, what behaviour would you expect in this case?

I'm not familiar with `DomainAutoDataAttribute` (which library is that from?) but, assuming it also derives from `DataAttribute` as does `ExampleAttribute`, then I would expect exactly the behaviour you describe. Two test runs, with one run with data coming from the `DomainAutoData` attribute, and another run coming from the `Example` attribute.

When generating tests for a given scenario, xbehave will enumerate each instance of an attribute which derives from `DataAttribute` and generate a set of tests for each one. This is exactly the same way that xunit generates tests for methods marked with `TheoryAttribute`.

**Comment by iamkoch** [comment]
Hi Adam

DomainAutoData is my own attribute - it extends AutoData from Mark Seeman's Autofixture.

Your explanation makes perfect sense now and I can see that I need to make a custom Example attribute that extends my AutoData attribute and this would resolve the issue.

Thanks for the quick response

**Comment by adamralph** [comment]
@iamkoch great!

I'd be very interested to see this in action if it's something you could share. It sounds like good material for a blog post or similar.

**Comment by iamkoch** [comment]
Hi Adam

I've just got this working by extending my own AutoData attribute and using some funky specimen builder logic to pull out the params based on the Position property of the Parameter.

I'll get a blog post up and link it here if anyone hits this issue in the future.

**Comment by iamkoch** [comment]
This is old now, but oddly it came up in conversation in the ddd-cqrs slack, and this post was found by a colleague. Small world... I made a Gist https://gist.github.com/iamkoch/81cecac9a3c5519a36801e01c8ab4968 with sample code.

**Comment by adamralph** [comment]
@iamkoch 👍 thanks for the update!

Out of interest, why is it that you need to create something custom, rather than using the built-in attributes in `AutoFixture`?

**Comment by iamkoch** [comment]
One example is that we have WebHost tests which run an in-memory Owin / Kestrel server. Our Attribute configures Autofixture to provide an instance of a fixture, as well as providing the ability to serve up dependencies (think mocks) directly from the webhost's IOC container

**Comment by adamralph** [comment]
@iamkoch is this something specific to xbehave, or would you have to do the same thing if you were using a regular xunit theory?

**Comment by iamkoch** [comment]
It's not XBehave specific. And I think I could just have extended InlineAutoData come to think of it. It's strange how one can't see the wood for the trees when you're frantically trying to solve a problem, instead of taking a step back and applying a bit of thought!

**Comment by iamkoch** [comment]
It's not XBehave specific. And I think I could just have extended InlineAutoData come to think of it. It's strange how one can't see the wood for the trees when you're frantically trying to solve a problem, instead of taking a step back and applying a bit of thought!

**Comment by adamralph** [comment]
I know the feeling @iamkoch 😄
