### ISSUE TITLE
Deprecate f() and _()

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#290]
`x()` should be used instead.

`f()` and `_()` will be deprecated in 2.x and removed in 3.0.0.

**Comment by ursenzler** [comment]
Why do you want to deprecate them? Can I still use them by making my own extension method?

**Comment by adamralph** [comment]
@ursenzler it's to get rid of redundant clutter. xbehave only really needs to provide one method and `x` seems like the natural choice. The others are a matter of taste. As you say, you can create your own synonyms for `x` using [extension methods](https://github.com/xbehave/xbehave.net/wiki/Defining-a-custom-step-method).

**Comment by enzian** [comment]
Hey, I would take this on, anybody mind?

**Comment by adamralph** [comment]
@enzian no objections at all, thank you very much!

I think it would be nice if the deprecation messages looked something like this https://github.com/config-r/config-r/blob/e24e1927b2383a5524c91e4d117c986ffc015f8e/src/ConfigR/ConfigExtensions.cs#L36

This deprecation would be released in xbehave 2.2.0.
