### ISSUE TITLE
Formatting of array arguments

### ISSUE THREAD

**Issue by ursenzler** [adamralph/xbehave.net#291]
In `XBehave.Test.Acceptance.ExampleFeature` is a spec that checks whether array arguments are formatted correctly (showing the values instead of System.Array). 
This Test is encapsulated with an `#if V2`.

When I use xBahave in my real project, arrays are not formatted correctly. Is this test ever executed?
I use xBehave.Core 2.0.1 in my project.

I'm confused?!?

**Comment by ursenzler** [comment]
Okay, I unconfused myself. The check runs as expected. Looked in the wrong project (linked projects confuse me :-) )

But I don't get why the arrays in my project are not formatted correctly.
I have a .Net 4.6.1 project that references 
`<package id="Xbehave.Core" version="2.0.1" targetFramework="net461" />`

Which results in a reference to `packages\Xbehave.Core.2.0.1\lib\portable-net45\Xbehave.Execution.desktop.dll`. 

Looks perfectly fine to me. But the test names contain System.Array for examples with arrays, instead of a list of the actual values.

Any ideas?

**Comment by adamralph** [comment]
Nothing really springs to mind. I guess I'd need to get my hands on an isolated repro of the bug...

**Comment by ursenzler** [comment]
The changes are not yet included in the release, they were made shortly after release 2.0.1.
I simply assumed they had to be in there because it was such a long time ago %-)

**Comment by adamralph** [comment]
@ursenzler yes, I missed that too. I'll continue the thread over at https://github.com/xbehave/xbehave.net/issues/267
