### ISSUE TITLE
Source stepping

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#298]
for reference, https://github.com/FakeItEasy/FakeItEasy/pull/736

**Comment by CaringDev** [comment]
... grab
Expect PR this weekend

**Comment by adamralph** [comment]
🎉 thanks!

**Comment by adamralph** [comment]
This has been released as a beta: https://www.nuget.org/packages/Xbehave/2.2.0-beta0003-build685

**Comment by adamralph** [comment]
Added to wiki: https://github.com/xbehave/xbehave.net/wiki/Debugging-scenarios#source-stepping
