### ISSUE TITLE
Support .NET Standard 1.1 (including .NET Core 1.0 onwards)

### ISSUE THREAD

**Issue by blairconrad** [adamralph/xbehave.net#300]
I'm willing to take a stab.

**Comment by adamralph** [comment]
@blairconrad thanks for raising this. Please be my guest!

**Comment by adamralph** [comment]
Re-opening to include upgrade to xunit 2.2 RTM.

**Comment by blairconrad** [comment]
Ha! I forgot that I was ever assigned this. I think that was after you closed it a year ago, @adamralph. Since you're on top of it, and I amn't likely to get time to work on it in the next bit, it's probably best to take my name off.
