### ISSUE TITLE
A minor issue related to the formatting of the tests

### ISSUE THREAD

**Issue by iam3yal** [adamralph/xbehave.net#349]
Hey, 

I'm not sure whether this relates to xbehave, xunit or ReSharper itself but at times I have tests like this:

``` C#
[Scenario]
public void ThrowArgumentNullException()
{
    $@"When the xmlCommandElement parameter is null 
        then the method {nameof(XmlCommandElementConverter.ToCommandModel)} 
        should throw {nameof(ArgumentNullException)}"
        .x(() => Action(() => {
                            XmlCommandElementConverter.ToCommandModel(xmlCommandElement: null);
                        }).ShouldThrow<ArgumentNullException>());
}
```

Now, at the display level of the unit test runner I get the following result:

```
When the xmlCommandElement parameter is null \r\n                then the method ToCommandModel \r\n                should throw ArgumentNullException
```

But I expect to get the following result:

```
When the xmlCommandElement parameter is null then the method ToCommandModel should throw ArgumentNullException
```

**Comment by adamralph** [comment]
hi @eyalsk, thanks for raising this.

Currently xbehave passes the exact text that you declare as the name of the step to xunit as the test "display name". If you use a multi-line literal as you have, then the line breaks and indents are part of that string. xunit then converts this into a C#-style string, so an end of line carriage return (CR) plus line feed (LF) becomes "\r\n".

We could introduce cleansing of the string in xbehave before passing it to xunit, i.e. remove CR and LF and multiple spaces/tabs. But before doing so, would the following workaround be OK for you?

``` C#
[Scenario]
public void ThrowArgumentNullException()
{
    ("When the xmlCommandElement parameter is null " +
        $"then the method {nameof(XmlCommandElementConverter.ToCommandModel)} " +
        $"should throw {nameof(ArgumentNullException)}")
        .x(() => Action(() => {
                            XmlCommandElementConverter.ToCommandModel(xmlCommandElement: null);
                        }).ShouldThrow<ArgumentNullException>());
}
```

This should result in the single line string which you desire.

**Comment by iam3yal** [comment]
@adamralph Well, yeah, I know I can do that but I really, really prefer not to do it, I mean the whole point is to keep things legible and as _close_ as possible to the source code. :)

p.s. thanks for the quick reply!

**Comment by adamralph** [comment]
@eyalsk fair enough, it is quite ugly. 😄 

The only thing I can think of then is to introduce string cleansing. I'm not against introducing this to xbehave, but before doing that, I want to make sure all the possible local solutions are discounted first so I hope you'll indulge me while I throw some crazy suggestions in here first.

I usually avoid regex, but how about this?

``` C#
[Scenario]
public void ThrowArgumentNullException()
{
    $@"When the xmlCommandElement parameter is null 
        then the method {nameof(XmlCommandElementConverter.ToCommandModel)} 
        should throw {nameof(ArgumentNullException)}".Clean()
        .x(() => Action(() => {
                            XmlCommandElementConverter.ToCommandModel(xmlCommandElement: null);
                        }).ShouldThrow<ArgumentNullException>());
}

// elsewhere
public static string Clean(this string text) => Regex.Replace(text, @"\s+", " ");
```

**Comment by iam3yal** [comment]
@adamralph Well, this can work but there are few issues with it.
1. People might not understand it so it means I'll have to document it.
2. People might forget to add it so I'd have to write a Roslyn analyzer for it or something similar to make sure it's enforced.
3. I'd have to have this method in every project or make a shared project for it and reference it.

I can probably somehow hook to xbehave and make the changes locally, is something like this possible? I really want this to happen at xbehave level if possible, I don't like workaround or hacks if I can avoid them, I like to solve problems at their root. :)

**Comment by adamralph** [comment]
@eyalsk those are all good points.

I'm starting to think this should indeed be built into xbehave. Can you think of any downside to passing every single step name through a cleansing method before using it in the test display name?

I guess one point is that there will be a performance hit but I'd hope it would be negligible, specially if we compile the regex as a static member.

The only other consideration I can think of is whether anyone would actually _desire_ the preservation of line breaks and indentation in the test names, but I'm struggling to think of a use case.

**Comment by iam3yal** [comment]
@adamralph Well, I can't really see any downsides to it and to be honest, the _name_ of the tests should never be formatted much like functions aren't formatted and people shouldn't rely on it, it doesn't make sense simply because the underlying tech, specifically, xunit and ReSharper don't account for it and you end up looking at unreadable test names.

I don't think it will have such a huge impact on performance, however, like anything I'd do a benchmark test and also try to do it without Regex at all.

These days, people tend to use Regex and LINQ instead of plain old imperative approach but really there's no need to kill flies with a sledgehammer. ;)

**Comment by iam3yal** [comment]
@adamralph 

I've made a simple benchmark, you can double check it and see whether I forgot something. :)

```
void Main()
{
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();

    string pattern = "\\s+";
    string singleSpace = " ";
    string text = "When the xmlCommandElement parameter is null \r\n                then the method ToCommandModel \r\n                should throw ArgumentNullException";

    // Warm up
    CleanString(text);
    Regex.Replace(text, pattern, singleSpace);
    Regex regex = new Regex(pattern, RegexOptions.Compiled);
    regex.Replace(text, singleSpace);

    // Benchmark
    Stopwatch sw = new Stopwatch();

    sw.Start();
    for (int i = 0; i < 1000000; i++)
    {
        CleanString(text);
    }
    sw.Stop();
    Console.WriteLine($"CleanString: {sw.Elapsed.TotalMilliseconds}");

    sw.Restart();
    for (int i = 0; i < 1000000; i++)
    {
        Regex.Replace(text, pattern, singleSpace);
    }
    sw.Stop();
    Console.WriteLine($"Regex: {sw.Elapsed.TotalMilliseconds}");

    sw.Restart();
    for (int i = 0; i < 1000000; i++)
    {
        regex.Replace(text, singleSpace);
    }
    sw.Stop();
    Console.WriteLine($"Regex (Compiled): {sw.Elapsed.TotalMilliseconds}");
}

public string CleanString(string text)
{
    StringBuilder sb = new StringBuilder();

    int spaces = 0;

    for (int i = 0; i < text.Length; i++)
    {
        char ch = text[i];

        if (char.IsControl(ch))
        {
        }
        else {
            if (char.IsWhiteSpace(ch))
            {
                spaces++;
            }
            else
            {
                spaces = 0;
            }

            if (spaces <= 1)
            {
                sb.Append(ch);
            }
        }
    }

    return sb.ToString();
}
```

**Comment by adamralph** [comment]
@eyalsk it seems imperative is the clear winner. Thanks for vindicating my usual reluctance to reach for regex 😉 

BTW, in this specific case, my feeling is that you are mixing together what I would normally consider to be at least two separate steps. The problem stems from the use of of an assert which also executes the action. My recommendation would be to use xunit's `Record.Exception` and split up action and assertion, e.g.

``` C#
[Scenario]
public void NullXmlCommandElement(Exception ex)
{
    "When converting a null XML command element to a command model"
        .x(() => ex = Record.Exception(() => XmlCommandElementConverter.ToCommandModel(null)));

    "Then an argument null exception is thrown"
        .x() => ex.ShouldBeOfType<ArgumentNullException>());
}
```

(Note that I've decoupled the scenario name and step names from the member names and C# language details.)

With this approach, which I would recommend, your immediate problem of the very long step name goes away.

**Comment by iam3yal** [comment]
@adamralph This is pretty neat, didn't know about it, I can certainly do that!

p.s. I have some recursive data structure that I test and it has multiple cases there, can you take a quick look and tell me how would you do it? not sure if it make sense to post it here, maybe in another issue or there's some other way I can contact you? like email or something?

**Comment by adamralph** [comment]
@eyalsk sure, I can take a look. You can post it in this issue if you want. I'm treating it as a discussion. If we want to pursue any changes in xbehave (such as the step name cleansing), we can spin those off into separate issues. I suggest we hold off on the step cleansing for now, at least until we've examined your use cases a little more.

If there's any code which you'd rather not post publicly then let me know and we can work out an alternative.

**Comment by adamralph** [comment]
BTW - I just noticed that my two step proposal was using a non-existent `element` variable. I've corrected and tidied it a little.

**Comment by blairconrad** [comment]
Hi. I'd been taking a long time to piece together a comment here, and you've all outpaced me.

I was going to suggest splitting the scenario into steps, as @adamralph has demonstrated.
And I had some other digressions, but I'm left with this:

If the step names are cleaned, then names that include whitespace or control characters will be mangled. (I know, that's the point, but hear me out.)
Perhaps I'm testing a tokenizer, and I want to see what happens when I feed it one or more spaces, tabs, or form feeds. If I write my step names to include the input, then all of a sudden I can't tell the steps apart.
The potential problem is compounded if I'm using an [`Example`](https://github.com/xbehave/xbehave.net/wiki/Scenarios-with-examples)).

Sure you can look at the inputs in a report, but the pretty step names are useless:

![image](https://cloud.githubusercontent.com/assets/3275797/19421847/6a98caba-93d8-11e6-895f-4363a9c33ed7.png)

So I'd recommend against any step name-mangling.

**Comment by adamralph** [comment]
A very good point @blairconrad. Thanks for chiming in. You succeeded where I failed, in thinking of a use case which would be broken by step name cleansing.

**Comment by blairconrad** [comment]
No problem. As you know, I'm always happy to argue against a feature or improvement!

**Comment by iam3yal** [comment]
@blairconrad You're right but we can also add this as an option that is turned off by default, @adamralph what do you think about this?

I don't mind marking some of my tests with `[Scenario(DisplayNameSterilization = true)]` or something similar.

p.s. Here is another test, I'd like your opinion about it because I'm not really happy about it. :)

```
[Scenario]
        public void ConvertToCommandModel(XmlCommandElement xmlCommandElement, ICommandModel commandModel)
        {
            $"Given an instance of {nameof(XmlCommandElement)} with existing items"
                .x(() => xmlCommandElement = new Fixture().Customize(new RecursiveCustomization {
                                                                         MaxDepth = 4,
                                                                         MaxElements = 3
                                                                     }).Create<XmlCommandElement>());

            $"When an instance of {nameof(XmlCommandElement)} is converted into an instance of {nameof(CommandModel)}"
                .x(() => commandModel = XmlCommandElementConverter.ToCommandModel(xmlCommandElement));

            $"Then at the 1st level the instance of {nameof(CommandModel)} needs to have a non-empty key"
                .x(() => commandModel.Key.Should().NotBeNullOrEmpty());

            $"And 3 instances of {nameof(CommandPropertyModel)} as its children"
                .x(() => commandModel.Properties.Should().HaveCount(3).And.ContainItemsAssignableTo<CommandPropertyModel>());

            $"And 3 instances of {nameof(CommandModel)} as its children"
                .x(() => commandModel.Children.Should().HaveCount(3).And.ContainItemsAssignableTo<CommandModel>());

            $"And at the 2nd level the children need to have 3 instances of {nameof(CommandModel)} as their children"
                .x(() => commandModel.Children.Should().Contain(c => c.Children.Count(m => m.As<CommandModel>() != null) == 3));

            $"And 3 instances of {nameof(CommandPropertyModel)}"
                .x(() => commandModel.Children.Should().Contain(c => c.Children.All(m => m.Properties.Count(p => p.As<CommandPropertyModel>() != null) == 3)));
        }
```

**Comment by blairconrad** [comment]
> I don't mind marking some of my tests with `[Scenario(DisplayNameSterilization = true)]` or something similar.

@eyalsk, of course an off-by-default option is a possibility, but if you're going to go that route, do not 2 of your 3 comments from https://github.com/xbehave/xbehave.net/issues/349#issuecomment-254048631 still apply?
- the option will require documentation, and
- people may forget to use it

Is it enough of an improvement to make it worth your while?

Oh, and if the scenario definitions are going to have to change anyhow, perhaps options (and I don't have a strong opinion here, as I expect never to use either of them) would be 
1. a different step invoker `x`, which cleans the step name, or
2. an extension method, which cleans the step name

I guess `[Scenario(DisplayNameSterilization = true)]` has the advantage of only needing to be done once per scenario. (Oh, for that matter, if an attribute that could be applied to a class (assembly?) could have even less impact.)

**Comment by iam3yal** [comment]
@blairconrad

> @eyalsk, of course an off-by-default option is a possibility, but if you're going to go that route, do not 2 of your 3 comments from #349 (comment) still apply? 

Yeah but in this case the context in which you apply the rule is part of the library and not part of the test itself, it's not some arbitrary method that you stuck in the test and you have to go figure what it does, it also reads better, however, enforcing it is kinda an issue but once you have it available as an attribute and like you pointed out it can be applied at the assembly level then you don't have to worry about it and I can easily document that.

I'd argue though that this needs to be the default behaviour, how many people are working on parsers? and put control characters inside their tests? but really either way I don't mind having it at the assembly level or per scenario and turn it on if this is unacceptable as the default behaviour.

> Is it enough of an improvement to make it worth your while?

Well, I have two options here either break these tests into multiple steps which is actually a good option like @adamralph wrote or having the option to keep some of my tests as they are and apply an attribute that sterilize the name, I can use both approaches where it make sense.

Whether it's worth it? well, I'm all for readability and this is the reason I picked xbehave so yeah I think it does. :)

> a different step invoker x, which cleans the step name

Yeah but @adamralph told me before that he doesn't want to add more of these in another issue that I've made, regardless, I think that it would be kinda strange to add another step invoker just for this, I really prefer the attribute approach as an option on the `Scenario` attribute.

> an extension method, which cleans the step name

Yeah but as I pointed out before this is actually something I'm against of for few reasons:
1. The name of the extension method won't really fit.
   
   `Clean` isn't a good method name for this because it's too generalized, `SterilizeControlCharacters` or `CleanControlCharacters` is okay, I can probably put XML comment to document what the method does but because the name suggests that this is a generalized purpose method people may wonder why I do it? they might not realize that the test name is _wrapped_ so in the documentation I'll have to provide extra information and write that this method sterilize control characters so the unit test runner would display it _correctly_ but wait! this is a generalized purpose method why do I make it specific to a testing environment? so I'll have to call it `XbehaveDisplayNameSterilization` or something similar which is ugly, verbose and odd. 
2. The extension method will be available to any string instance and I don't think I want that.
3. The extension method is a rule/option to force xbehave clean the control characters so I really think it needs to be part of xbehave. 

> I guess [Scenario(DisplayNameSterilization = true)] has the advantage of only needing to be done once per scenario. (Oh, for that matter, if an attribute that could be applied to a class (assembly?) could have even less impact.)

Exactly my thoughts. :)

I hope it make sense!

**Comment by blairconrad** [comment]
> how many people are working on parsers? 

I've no idea. My team, sometimes.

> and put control characters inside their tests?

My team, sometimes. Well, usually whitespace.

Of course, all this is just anecdotal. Like how you were the first person I'd ever heard of who wanted to put non-significant whitespace in a step name. We each have reports of what I'd guess are corner cases.

**Comment by iam3yal** [comment]
@blairconrad 

> Of course, all this is just anecdotal. Like how you were the first person I'd ever heard of who wanted to put non-significant whitespace in a step name. We each have reports of what I'd guess are corner cases.

Yeah, I agree. :)

**Comment by adamralph** [comment]
@eyalsk this is what I might do with the scenario you posted:

``` C#
[Scenario]
public void RecursiveConversion(XmlCommandElement xmlCommandElement, ICommandModel commandModel)
{
    "Given an XML command element with child elements"
        .x(() => xmlCommandElement = new Fixture().Customize(
            new RecursiveCustomization {
                MaxDepth = 4,
                MaxElements = 3
            }).Create<XmlCommandElement>());

    "When I convert the element to a command model"
        .x(() => commandModel = XmlCommandElementConverter.ToCommandModel(xmlCommandElement));

    "Then the key is not empty"
        .x(() => commandModel.Key.Should().NotBeNullOrEmpty());

    "And there are three command property models"
        .x(() => commandModel.Properties.Should().HaveCount(3)
            .And.ContainItemsAssignableTo<CommandPropertyModel>());

    "And there are three child command models"
        .x(() => commandModel.Children.Should().HaveCount(3)
            .And.ContainItemsAssignableTo<CommandModel>());

    "And each child has three child command models"
        .x(() => commandModel.Children.Should().Contain(c =>
            c.Children.Count(m => m.As<CommandModel>() != null) == 3));

    "And each child has three command property models"
        .x(() => commandModel.Children.Should().Contain(c => c.Children.All(m =>
            m.Properties.Count(p => p.As<CommandPropertyModel>() != null) == 3)));
}
```

Generally, if you're using `$"... { ... } ..."` as a step name and putting anything inside `{ ... }` which isn't an `[Example]` value, I'd say that's probably a code smell.

More generally, I'm leaning towards the need for step name cleansing being an edge case which we can usually avoid by revisiting the step names.

**Comment by iam3yal** [comment]
@adamralph Thanks for the reply, I'd change the tests based on your suggestions.

> Generally, if you're using $"... { ...} ..." as a step name and putting anything inside { ... } which isn't an [Example] value, I'd say that's probably a code smell.

Can you elaborate farther on this? I don't think I understood your point here. :)

**Comment by adamralph** [comment]
@eyalsk it's somewhat of a sidebar to this discussion, but see [examples](https://github.com/xbehave/xbehave.net/wiki/Scenarios-with-examples). When using examples, it's reasonable to write `$"Given the number {x}"` as a step name, since having the example value in there is useful.

BTW - I believe this is only of academic interest at this point, but if you _still_ find a need to introduce the cleansing/sterilization, it's quite trivial to do this using a [step filter](https://github.com/xbehave/xbehave.net/wiki/Step-filters), e.g.

``` C#
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Xbehave;
using Xbehave.Sdk;

namespace Foo
{
    public class Bar
    {
        [Scenario]
        [SterilizeStepNames]
        public void Baz()
        {
            @"Given
            a muli-line
            and indented step name"
                .x(() => { });
        }
    }

    public sealed class SterilizeStepNamesAttribute : Attribute, IFilter<IStepDefinition>
    {
        public IEnumerable<IStepDefinition> Filter(IEnumerable<IStepDefinition> steps)
        {
            foreach (var step in steps)
            {
                step.Text = Regex.Replace(step.Text, @"\s+", " "); // TODO: kill the regex!
                yield return step;
            }
        }
    }
}

```

Without the attribute:

![image](https://cloud.githubusercontent.com/assets/677704/19443459/210a3ca2-948d-11e6-9a83-6e26a576a22e.png)

With the attribute:

![image](https://cloud.githubusercontent.com/assets/677704/19443443/136cb782-948d-11e6-8111-a67a3e60296f.png)

Note that you can apply a filter attribute at the method (scenario), class or assembly level. You could even package the attribute in a NuGet package, as an extension to xbehave.

**Comment by iam3yal** [comment]
@adamralph Thank you so much! I really appreciate it.

Keep up the good work!

**Comment by adamralph** [comment]
@eyalsk you're welcome. I'm glad you're enjoying xbehave!
