### ISSUE TITLE
investigate use with ApprovalTests

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#35]
3/24/2013
 DavidSiew1
Hey Adam, I was wondering if you knew how to get your framework to work with approval tests http://approvaltests.sourceforge.net/
7:22:52 PM
3/25/2013
 adamral.ph
hi David, yes you can use whatever assertion library you like with xBehave
8:19:36 AM
as for approvaltests, it looks like it is based on NUnit, is that correct? if so, then it won't work with xbehave
8:20:39 AM
DavidSiew1 just entered xbehavenet
9:06:16 AM
 DavidSiew1
Hi Adam. Approval tests also work with NUnit
9:07:02 AM
sorry
9:07:04 AM
XUnit
9:07:06 AM
it's just that it's not recognising the "Specification" attribute
9:08:07 AM
I tried to follow the instructions here http://stackoverflow.com/questions/12054138/how-to-add-support-for-xunits-theory-attribute-in-approvaltests which refers to theory but couldn't get it working
9:09:14 AM
DavidSiew1 left xbehavenet (plus 4 hidden... click to expand)
3:11:01 PM
 adamral.ph
ok, I'll take a look if I get some time
8:12:42 PM

**Comment by togakangaroo** [comment]
Anyone take a look at this? The issue is typically that ApprovalTests is checking the stacktrace and not finding a good test name to use. I've added (lame) support to Subspec before by doing

```
 Approvals.Verify(
new ExistingFileWriter(fileToVerify.FullName), 
new ConstantNamer(Core.CurrentlyExecutingAssertion), Approvals.GetReporter()
);
```

Where

```
public class ConstantNamer : IApprovalNamer
{
    public string SourcePath { get { return defaultNamer.SourcePath; } }
    public string Name { get; private set; }
    public ConstantNamer(string name) {
        Name = Path.GetInvalidPathChars().Aggregate(name, (path, c) => path.Replace(c, ' ')).Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).Join(" ");
    }

    readonly IApprovalNamer defaultNamer = Approvals.GetDefaultNamer();

    static ConstantNamer() {
        if (!StackTraceParser.GetParsers().OfType<SubspecStackTraceParser>().Any())
            StackTraceParser.AddParser(new SubspecStackTraceParser());
    }
}
```

and I had to add a static

```
                Core.CurrentlyExecutingAssertion = String.Format( "{0}, {1}", name, assertion.Message );
```

to Subspec basically relying on single-threading of tests

**Comment by adamralph** [comment]
Hi @togakangaroo I'm afraid I never got round to looking at this. I've never used ApprovalTests myself and you're the first person to ask about it since that original question.

Would you be able to give it a try and see what you can find it out? Any help you could offer on this would be hugely appreciated.

**Comment by adamralph** [comment]
BTW - xBehave.net 2.0 is due out any day now and it is a complete re-write (as is xUnit.net 2.0), so it may not be worth spending too much time getting this working with 1.x.

**Comment by togakangaroo** [comment]
Best I can promise is that checking this out will go not as far to the back of my queue as some other things.

In the meantime this hacky thing works:

```
        [Scenario]
        public void ParsingComplexResults(NpiResultsParser.NpiDoctorDataParser parser) {
            "Given a doctor parser from a parsed list of npi results".x(() => parser = loadSampleFileIntoParser().GetDoctorParser("1255637005"));
            jsonApproval("Can parse name", () => parser.GetNameParts());
            jsonApproval("Can parse addresses", () => parser.GetAddresses()); //primary address should be first
            jsonApproval("Can parse taxonomies", () => parser.GetTaxonomies()); //primary license should be first
        }

        void jsonApproval(string name, Func<object> getValue) {
            var st = new StackTrace();
            var testName = "{0} {1} {2}".Fmt(this.GetType().Name, st.GetFrame(1).GetMethod().Name, name).Replace(" ", "_");
            name.x(() => Approvals.Verify(
                new ApprovalTextWriter(JsonConvert.SerializeObject(getValue(), Formatting.Indented), "json"),
                new ConstantNamer(testName), new MultiReporter(new FileLauncherReporter(), new PowerShellClipboardReporter())
                ));
        }
    public class ConstantNamer : IApprovalNamer
    {
        public string SourcePath { get { return defaultNamer.SourcePath; } }
        public string Name { get; private set; }
        public ConstantNamer(string name) {
            Name = Path.GetInvalidPathChars().Aggregate(name, (path, c) => path.Replace(c, ' ')).Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).Join(" ");
        }

        readonly IApprovalNamer defaultNamer = Approvals.GetDefaultNamer();

        static ConstantNamer() {
            if (!StackTraceParser.GetParsers().OfType<XbehaveStackTraceParser>().Any())
                StackTraceParser.AddParser(new XbehaveStackTraceParser());
        }
        public class XbehaveStackTraceParser : AttributeStackTraceParser
        {
            public override bool Parse(StackTrace trace) {
                base.Parse(trace);
                //This should work but for some reason doesn't http://stackoverflow.com/questions/26553231/why-can-i-not-find-a-custom-attribute-on-this-methodinfo
                //this.approvalFrame = caller.NonLambdaCallers.FirstOrDefault(c => c.Method.GetCustomAttributes(typeof (SpecificationAttribute), true).Any());
                //instead this is a little fragile but should work.
                this.approvalFrame = caller.NonLambdaCallers.Last(c => c.Class.Namespace.Split('.').Contains("AppleHms"));
                return this.approvalFrame != null;
            }

            public override string ForTestingFramework {
                get { return "xUnit.net"; }
            }

            protected override string GetAttributeType() {
                return typeof(ScenarioAttribute).FullName;
            }
        }

    }
```

**Comment by adamralph** [comment]
Thanks @togakangaroo!

In the meantime I've linked to here in the [FAQ](https://github.com/xbehave/xbehave.net/wiki/FAQ).

**Comment by adamralph** [comment]
@togakangaroo I'm closing this issue since the solution will have to exist either reflectively in ApprovalTests itself or in a third party package providing integration between ApprovalTests and xbehave. Thanks for your investigation into this, which has been linked from the FAQ.
