### ISSUE TITLE
restore packages before building

### ISSUE THREAD

**Issue by blairconrad** [adamralph/xbehave.net#368]
When I check out a shiny new sandbox (or clean my existing one) and build, I see a failure:

```
λ git clean -x -f -d
λ .\build.cmd
simple-targets: Running "default"...
simple-targets/build: Starting...
Running '"dotnet" build ./**/project.json -c Release'...
Project Xbehave.Core does not have a lock file. Please run "dotnet restore" to generate a new lock file.
Project Xbehave.Core does not have a lock file. Please run "dotnet restore" to generate a new lock file.
simple-targets/build: Failed! The command exited with code 1.
```

There's a perfectly good `restore` target in `build.csx` that's not connected to anything. Let's hook it up!

**Comment by blairconrad** [comment]
Um. We may want to hold off on this. I missed a bit of the instruction:

> Navigate to your clone root folder and **execute dotnet restore** followed by build.cmd.

Although having an orphaned `restore` task still confuses me a bit.

For my education, why not restore each time? Speed?

**Comment by adamralph** [comment]
> For my education, why not restore each time? Speed?

Exactly that. This also mimics the raw usage of `dotnet.exe`, i.e. `dotnet restore`, `dotnet build`.

More generally, I'd love to stop using build scripts entirely and just use `dotnet` for the whole workflow, but there are gaps which I'm not sure will ever be sealed, e.g. the sourcelink and nuspec munging that is being done in the build.csx here.

**Comment by blairconrad** [comment]
> there are gaps which I'm not sure will ever be sealed

Thanks for the chat, and sorry for the issue/PR noise!

**Comment by adamralph** [comment]
No problem @blairconrad. I appreciate the intention!
