### ISSUE TITLE
Scenarios with examples cause build failures with xunit's new analyzers

### ISSUE THREAD

**Issue by michael-wolfenden** [adamralph/xbehave.net#372]
Given the following packages:

```xml
<PackageReference Include="Xbehave" Version="2.2.0-beta0003-build685" />
<PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
```

The following code:

```csharp
[Scenario]
[Example(1, 2, 3)]
[Example(2, 3, 5)]
public void Addition(int x, int y, int expectedAnswer, Calculator calculator, int answer)
{
    "Given the number {0}"    // or in C# 6 or later, $"Given the number {x}"
        .x(() => { });

    "And the number {1}"
        .x(() => { });

    "And a calculator"
        .x(() => calculator = new Calculator());

    "When I add the numbers together"
        .x(() => answer = calculator.Add(x, y));

    "Then the answer is {2}"
        .x(() => Assert.Equal(expectedAnswer, answer));
}
```

Results in the following build exception:

`xUnit1005 - Fact methods should not have test data`

I assume this is due to xunit's new analyzers which check that tests with the `[Fact]` attribute do not get test data passed to them.

Since`[Scenario]` derives from `[Fact]` the analyzer gets triggered.

**Comment by adamralph** [comment]
Hmmm... interesting! The rule seems overbearing, since the use of a single attribute to mark scenarios, with or without examples is a deliberate design in xbehave, and I'd argue it's not unreasonable. Perhaps the analyzer should respect some kind of opt out from this error for derived attributes.

@bradwilson any thoughts?

Thanks for raising this @michael-wolfenden.

**Comment by bradwilson** [comment]
Agreed that the rule seems wrong. It should only trigger for methods which exactly use `[Fact]`, but not for any derived types. Please [open an issue](https://github.com/xunit/xunit/issues). /cc @marcind

**Comment by adamralph** [comment]
Thanks for raising the xunit issue @marcind

I'll close this issue now since the fix will be in xunit and we can track the issue there.
