### ISSUE TITLE
System.TypeLoadException : Could not load type 'Xunit.Sdk.LongLivedMarshalByRefObject'

### ISSUE THREAD

**Issue by osotorrio** [adamralph/xbehave.net#374]
**Preconditions**

1. I am using Visual Studio Community 2015 Update 3.
2. NUnit 3 Test Adapter 3.8.0.0 extension is installed in VS.
3. My projects, including the test project, target .net Framework 4.6.1

4. This is my packages.config file:

```xml  
  <package id="Xbehave" version="2.1.4" targetFramework="net461" />
  <package id="Xbehave.Core" version="2.1.4" targetFramework="net461" />
  <package id="xunit" version="2.2.0" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net461" />
  <package id="xunit.assert" version="2.2.0" targetFramework="net461" />
  <package id="xunit.core" version="2.2.0" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.2.0" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.2.0" targetFramework="net461" />
  <package id="xunit.runner.console" version="2.2.0" targetFramework="net461" developmentDependency="true" />
  <package id="xunit.runner.visualstudio" version="2.2.0" targetFramework="net461" developmentDependency="true" />
```
When I run the test from both, the console runner and the VS runner, I get the following exception:

> ------ Run test started ------
> [xUnit.net 00:00:00.2586974]   Discovering: MyFirstUnitTest
> [xUnit.net 00:00:00.4511432]   Discovered:  MyFirstUnitTest
> [xUnit.net 00:00:00.7579004]   Starting:    MyFirstUnitTest
> [xUnit.net 00:00:00.9129035]     MyFirstUnitTest.CalculatorFeature.Addition [FAIL]
> [xUnit.net 00:00:00.9151382]       System.TypeLoadException : Could not load type 'Xunit.Sdk.LongLivedMarshalByRefObject' from assembly 'xunit.execution.desktop, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.
> [xUnit.net 00:00:00.9168246]       Stack Trace:
> [xUnit.net 00:00:00.9178671]            at Xbehave.Execution.ScenarioRunnerFactory.Create(Object[] scenarioMethodArguments)
> [xUnit.net 00:00:00.9184913]         C:\projects\xbehave-net\src\Xbehave.2.Execution.desktop\ScenarioOutlineRunner.cs(81,0): at Xbehave.Execution.ScenarioOutlineRunner.<AfterTestCaseStartingAsync>d__8.MoveNext()
> [xUnit.net 00:00:00.9453067]   Finished:    MyFirstUnitTest
> ========== Run test finished: 1 run (0:00:01.2002505) ==========

**Comment by adamralph** [comment]
@osotorrio thanks for raising this.

@bradwilson did anything change between xunit 2.1.0 and 2.2.0 wrt `Xunit.Sdk.LongLivedMarshalByRefObject`?

**Comment by bradwilson** [comment]
No.

**Comment by bradwilson** [comment]
To be clear, we're talking about `xunit.execution.desktop`, targeting desktop CLR, right?

**Comment by bradwilson** [comment]
Looking at your [NuGet package](https://www.nuget.org/packages/XBehave), I'm pretty sure this is not right:

> xunit (>= 2.1.0 && < 3.0.0)

First, you should be strongly linked against a version. If you've linked against 2.1.0, then they *must* also link against 2.1.0. We do not practice SemVer, and we may break things from build to build.

Second, you should probably link against `xunit.extensibility.core` (and/or `xunit.extensibility.execution`) rather than `xunit`, since the latter brings in xUnit.net's assertion library (which I presume you are not mandating the use of).

**Comment by adamralph** [comment]
Thanks @bradwilson.

> To be clear, we're talking about xunit.execution.desktop, targeting desktop CLR, right?

I believe so. From the issue description it appears that @osotorrio is using .NET FX 4.6.1 throughout.

> First, you should be strongly linked against a version. If you've linked against 2.1.0, then they must also link against 2.1.0. We do not practice SemVer, and we may break things from build to build.

OK, that's news to me. I'll do that, but it does put a burden on me to release a new version of xbehave with every single xunit release. What about patch increments? Could they also break, or could I have a version range of, say, [2.2.0, 2.3.0)?

> Second, you should probably link against `xunit.extensibility.core` (and/or `xunit.extensibility.execution`) rather than `xunit`, since the latter brings in xUnit.net's assertion library (which I presume you are not mandating the use of).

`xbehave` depends on `xunit`, and `xbehave.core` depends on `xunit.core`. This was a deliberate choice to make the mapping between `xbehave` and `xunit` packages easier to understand, with the knowledge that `xunit`, and therefore `xbehave`, will bring in the assertion lib.

**Comment by osotorrio** [comment]
After reading your comments I have started over. I uninstalled all the packages from the solution. Then I installed just Xbehave 2.1.4. So in this case, I did not update to XUnit 2.2.0 after the installation of XBehave 2.1.4.

This is how the packages.config looks now.

 ```xml
 <package id="Xbehave" version="2.1.4" targetFramework="net461" />
  <package id="Xbehave.Core" version="2.1.4" targetFramework="net461" />
  <package id="xunit" version="2.1.0" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net461" />
  <package id="xunit.assert" version="2.1.0" targetFramework="net461" />
  <package id="xunit.core" version="2.1.0" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.1.0" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.1.0" targetFramework="net461" />
  <package id="xunit.runner.console" version="2.2.0" targetFramework="net461" developmentDependency="true" />
```

When I run the test from the console runner I get the following error message.

> xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
> System.IO.FileLoadException: Could not load file or assembly 'xunit.execution.desktop, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> System.IO.FileLoadException: Could not load file or assembly 'xunit.execution.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I am not sure now if there is something wrong on my side!!

**Comment by adamralph** [comment]
@osotorrio thanks very much for the update!

I notice that you are still using `xunit.runner.console` 2.2.0. Can you please confirm if you get the same problem if you use `xunit.runner.console` 2.1.0?

**Comment by osotorrio** [comment]
Yes, I am afraid that I get the same type of exception:

> xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
> System.IO.FileLoadException: Could not load file or assembly 'xunit.execution.desktop, Version=2.2.0.3545, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> System.IO.FileLoadException: Could not load file or assembly 'xunit.execution.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

how else can I help?

**Comment by bradwilson** [comment]
I'm very confused how you are linked against both 2.1 and 2.2. Can you create a stand-alone repro?

**Comment by osotorrio** [comment]
Preparing the stand-alone repo I realized what was the problem. After installing Xbehave 2.1.4, if you update all the XUnit's packages to 2.2.0, it creates some assembly bindings in the app.config. That is why the "double link".

[https://github.com/osotorrio/stand-alone](https://github.com/osotorrio/stand-alone)

Following the commits you can see the application working and not working. 

Commit [8a9ce48](https://github.com/osotorrio/stand-alone/commit/8a9ce483ad859cfd0d058a8b7325a5fe68bd25ea): 	
Installed XBehave 2.1.4 and xunit.runner.console 2.1.0. IT IS WORKING!!

Commit [de1ae0c](https://github.com/osotorrio/stand-alone/commit/de1ae0c2bed868c29e8d12e7c55fad3cce1b50de):
Updated all XUnit packages. IT IS NOT WORKING!! (I guess that should not happen)

Commit [bef5a6d](https://github.com/osotorrio/stand-alone/commit/bef5a6d3bd05b325993a43642a14de4f605b2853):
Going back to the XUnit 2.1.0. IT IS NOT WORKING!! (I guess it should remove the [assembly bindings](https://github.com/osotorrio/stand-alone/commit/de1ae0c2bed868c29e8d12e7c55fad3cce1b50de#diff-8e8771b302fd114219b3a46cea7b3c92))

Commit [8ac5b80](https://github.com/osotorrio/stand-alone/commit/8ac5b8012a7f3b8602067f1428ca7547ee345521):
Removed app.config. IT IS WORKING AGAIN!!

I apologize for not realizing about the bindings before :(

**Comment by fleetr** [comment]
@adamralph
>did anything change between xunit 2.1.0 and 2.2.0 wrt Xunit.Sdk.LongLivedMarshalByRefObject?

Yes, it did - in 2.1.0 that class lived in the Xunit.Sdk namespace, but in >=2.2.0 it _can_ live in the Xunit namespace, depending on some conditional compilation thus:

```csharp
#if XUNIT_FRAMEWORK
    namespace Xunit
#else
    namespace Xunit.Sdk
#endif
```

**Comment by adamralph** [comment]
It looks like this discussion has run it's course, and I believe the best course of action is to release a new version of xbehave which links against xunit 2.3. I've raised https://github.com/xbehave/xbehave.net/issues/375 for that.

**Comment by jotatoledo** [comment]
Just came across this issue. Just to be clear, there is no version of `xbehave` compatible with `xunit` 2.2.0, right? If thats the case, thats (atm) a deal breaker for me, as I cant update xunit to 2.3.x :(

**Comment by adamralph** [comment]
@jotatoledo that's correct. There is no xbehave version linked against xunit 2.2.

Out of interest, why can you not upgrade to xunit 2.3?

**Comment by jotatoledo** [comment]
@adamralph thanks for the quick reply. Im currently using a visual studio extension to run my tests + code cover, which has no compatibility with xunit 2.3.x. I might upgrade in the future, but its not in my plans atm.

**Comment by adamralph** [comment]
@jotatoledo I see, thanks. Out of curiosity, I'm going to investigate how it easy it will be to release xbehave 2.2, linked to xunit 2.2.

**Comment by jotatoledo** [comment]
That would be great, but if the effort to make it happen is too much, I would understand if such a release doesnt see the light. I will open a new issue so that if more ppl require support for xunit 2.2.x are out there, they can upvote it or comment it.

**Comment by adamralph** [comment]
@jotatoledo perfect, thanks very much! 👌
