### ISSUE TITLE
Tests are Inconclusive and non discoverable with latest version of Xbehave and Xunit with dotnet core 2.0

### ISSUE THREAD

**Issue by Saisuryakattamuri** [adamralph/xbehave.net#376]
I'm using the following
XUnit 2.3.0
XBehave 2.1.4
dotnet core 2.0

When I tried to run sample XBehave Scenario(exactly the one given in Quickstart) I'm getting error saying Addition is InConclusive with the following stacktrace. [xbehave.txt](https://github.com/xbehave/xbehave.net/files/1390695/xbehave.txt)

I have referred to issue #373  and disabled ReSharper and executed tests only with VisualStudio.
Still the tests are not discoverable.

Tried with dotnet-xunit cli runner too,still it says no Tests are found in Test.dll

![capture](https://user-images.githubusercontent.com/24825882/31659994-99a95e8c-b353-11e7-83bf-b8a93815abdf.PNG)

**Comment by adamralph** [comment]
@Saisuryakattamuri thanks for raising this.

Indeed, xBehave.net 2.1.4 does not support either .NET core or xUnit.net 2.3.0.

xBehave.net 2.3.0 will add support for both [.NET core](https://github.com/xbehave/xbehave.net/issues/300) and [xUnit.net 2.3.0](https://github.com/xbehave/xbehave.net/issues/375). I don't have an ETA yet for xBehave.net 2.3.0 but, coincidentally, I started work on it last weekend.

In the meantime, you can try the latest xBehave.net pre-release (2.2.0-beta0003-build685).

**Comment by adamralph** [comment]
@Saisuryakattamuri assuming you've got things working for now, I'm closing this issue. Thanks for raising it. Please keep an eye on the repo for the 2.3.0 release and/or follow our [Twitter account](https://twitter.com/xbehavenet) for updates. If you have any further questions please re-open this issue or raise a new one.
