### ISSUE TITLE
Analyzer warning for code outside step delegates

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#406]
The basic premise of xbehave is that _everything_ should be inside step delegates so that success or failure of a given scenario always related to a specific logical step, identified by a natural language sentence. If code is outside a step delegate, then this benefit is lost.

Slightly contrived example:

```C#
[Scenario]
public void Addition(int x, int y, Calculator calculator, int answer)
{
    "Given the number 1"
        .x(() => x = 1);

    "And the number 2"
        .x(() => y = 2);

    calculator = new Calculator());       // this could potentially throw

    "When I add the numbers together"
        .x(() => calculator.Add(x, y));

    answer = calculator.GetLastAnswer();  // this could potentially throw

    "Then the answer is 3"
        .x(() => Xunit.Assert.Equal(3, answer));
}
```

If one of the two commented operations throw, it's not possible to tell any more from the natural language output which one of them threw. It is necessary to resort to inspecting the call stack, which is the case when not using xbehave. Thus, the main benefit of xbehave is lost.

**Comment by ursenzler** [comment]
We typically initialize some values at the beginning of a scenario (outside of a step). And I think that is okay because this code really should not fail. If it does, the whole scenario fails, which is okay with my understanding.
So the analyzer should probably only check for code after the first step.

Btw `answer = calculator.GetLastAnswer();` is something that we would encapsulate with a dummy step - as I mentioned in #362: `"_".x(() => answer = calculator.GetLastAnswer());`

**Comment by adamralph** [comment]
> We typically initialize some values at the beginning of a scenario (outside of a step).

Why not put that in a step? It can even go into a [background step](https://github.com/xbehave/xbehave.net/wiki/Backgrounds) if you want to reuse across scenarios.

> Btw `answer = calculator.GetLastAnswer();` is something that we would encapsulate with a dummy step - as I mentioned in #362: `"_".x(() => answer = calculator.GetLastAnswer());`

Why does it have to be a "dummy" step? If you are writing a step anyway, I'd give it a proper sentence:

```C#
"And I get the last answer"
    .x(() => answer = calculator.GetLastAnswer());
```

**Comment by ma499** [comment]
> Why not put that in a step?

I agree with _initiatlisation_ in a step - that's how I interpret 'Given' steps.

However, I find it a bit ugly for test _variables_ to be declared as method parameters - particularly when the test also has parameters that I'm driving using `[Example(..)]`. I would prefer to _declare_ test variables inside the method. The [documentation seems to suggest that this is acceptable](https://github.com/xbehave/xbehave.net/wiki/Writing-scenarios#parameters).

**Comment by adamralph** [comment]
@ma499 that's a fair point. I guess it's a matter of taste. I guess such an analyzer could attempt ignore variable declarations, but it's always the edge cases that trip up those kind of things.

**Comment by adamralph** [comment]
Will be made redundant by #362.
