### ISSUE TITLE
failing tests are shown as ignored in Resharper Runner

### ISSUE THREAD

**Issue by ursenzler** [adamralph/xbehave.net#408]
I'm not done isolating the reason because we did the following in our solution:
- updated all projects to the new csproj format (Target = net47)
- updated xunit to 2.3.1
- added xunit.runners.visualstudio

I tested the behavior with xBehave.Core 2.1.4 and 2.3.0-rc0001-build717.

When a Scenario fails, it is shown as ignored in the Resharper runner inside VisualStudio and the steps are not shown as tests - for both succeeding as well as failing Scenarios.

Before I spend more time analyzing, maybe someone already hit that problem and can help me.

**Comment by ursenzler** [comment]
So I played around with different versions.

Everything works as expected in the console runner.

However, when using the xunit.runner.visualstudio Resharper shows Scenarios without steps. 
This holds for xunit.runner.visualstudio 2.1.0 running xBehave 2.1.4 (which uses xunit 2.1.0) as well as for xunit.runner.visualstudio 2.3.1 running xbehave 2.3,0-rc0001-build717

As long as the versions match, the Scenario is shown as failed. But sadly, no steps.

Running the same in a project with the "classic" csproj and therefore without the xunit.runner.visualstudio, the steps are shown.

So it seems to me, that the problem is with xunit.runner.visualstudio and that xbehave has a problem with reporting steps as tests. Besides, how was R# able to run Scenarios in the old format when there was no explicit runner?!

@adamralph yes I know, you don't use R# ;-)

**Comment by adamralph** [comment]
@ursenzler which version of R# are you using? Have you seen this? https://github.com/xbehave/xbehave.net/wiki/Scenarios-are-shown-as-a-single-test-in-ReSharper-instead-of-a-test-for-each-step

**Comment by ursenzler** [comment]
@adamralph I used to latest official release (2017.2.2). I'll try with the EAP and report back.

**Comment by ursenzler** [comment]
I can confirm that R# EAP 2017.3 solves this issue. 
Thanks for the link and once again it is not the failure of xBehave ;-)

**Comment by adamralph** [comment]
👍 great!
