### ISSUE TITLE
Background steps showing as dummy inconclusive tests in ReSharper

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#410]
_Outcome of #409._

![image](https://user-images.githubusercontent.com/677704/33805285-8117cca4-ddb6-11e7-84d2-ff1862786fce.png)

This is because `[Background]` is redundantly inheriting from `[Fact]`. It's arguable that ReSharper should not be showing the test at all, as other runners do, but in any case, the inheritance is redundant and can be removed, which will fix this problem immediately, regardless of any changes to ReSharper.

Thanks to @eyalsk for discovering this.

**Comment by adamralph** [comment]
@eyalsk I've released https://www.nuget.org/packages/Xbehave/2.3.1-alpha0001-build731 which contains a fix for this problem. Would you be able to give it a try to verify?

**Comment by iam3yal** [comment]
@adamralph Sure! 😄

**Comment by iam3yal** [comment]
@adamralph It seems to work great, have you implemented the ability to change where the `(Background)` text appears?

**Comment by adamralph** [comment]
@eyalsk great, thanks for verifying.

> have you implemented the ability to change where the (Background) text appears?

Not yet, watch https://github.com/xbehave/xbehave.net/issues/411 for updates on that.

**Comment by adamralph** [comment]
Released in 2.3.1 - https://twitter.com/adamralph/status/998611366817746944

Thanks @eyalsk. Look out for your name in the release notes! https://github.com/xbehave/xbehave.net/releases/tag/2.3.1 🏆
