### ISSUE TITLE
.NET Core 

### ISSUE THREAD

**Issue by coderitual** [adamralph/xbehave.net#439]
Is this framework working only with dotnetcore dependency? I am looking for a cross platform solution.

**Comment by blairconrad** [comment]
@coderitual, xBehave.net targets both .NET Standard 1.1 as well .NET Framework 4.5.2, so can be used under both .NET Core and .NET Framework.

**Comment by adamralph** [comment]
@coderitual thanks for raising this question.

As @blairconrad says, xBehave.net supports .NET standard 1.1, which means all the following platforms are supported (and all later versions of each):

- .NET Core 1.0
- .NET Framework 4.5
- Mono 4.6
- Xamarin.iOS 10.0
- Xamarin.Mac 3.0
- Xamarin.Android 7.0
- UWP 10.0
- Windows 8.0
- Windows Phone 8.1

... plus any other platform which supports .NET Standard 1.1 or later.

See [.NET Standard Versions](https://github.com/dotnet/standard/blob/master/docs/versions.md) for more info.
