### ISSUE TITLE
do you have a preferred solution for generating a .md report from the test results?

### ISSUE THREAD

**Issue by paulvanbladel** [adamralph/xbehave.net#483]
I'm using .net core. 
Can't find a working solution for generating an .md file from the test results.
Suggestions?
Thanks a million.
cheers
paul.

**Comment by adamralph** [comment]
Hi @paulvanbladel, I'm afraid not.

xbehave has never provided such a facility for any platform. The best I can suggest is https://github.com/appccelerate/xBehaveMarkdownReport but that only works against the XML output from `xunit.console.exe`, and not the `trx` output from `dotnet test`. I see you've already raised an issue over there.

BTW, it looks like there may be a [way of getting `trx` output in xunit format](https://stackoverflow.com/a/43482928/49241), but I've never tried it.

**Comment by paulvanbladel** [comment]
Great info.
I tried it, and indeed that xunit logger works , but unfortunately the output is not rich enough for xBehaveMarkdownReport.
It's a pity because xbehave without reporting decimates the total value. The real added value comes in when you can communicate with business party in terms of BDD tests.

**Comment by adamralph** [comment]
> xbehave without reporting decimates the total value

I guess that's where we disagree. 😄 

I haven't added this to xbehave because I have no use for it. If it's something you need, you're welcome to contribute the functionality. That said, it wouldn't require any dependency on the core package, so it can be it's own independent project and package. (Hint: https://github.com/new) 😉

**Comment by paulvanbladel** [comment]
there is nothing that can decimate the value of xbehave.😊 I meant that xbehave without a complementary reporting solution decimates the value of doing BDD. I am a strong believer of the "doing one thing and do it well principle". So indeed xbehave should definitely not contain reporting. It is more than fine in its current form.
i am still in the process of discovering bdd but if everything goes well i think i will soon develop a corresponding report solution. 😊
cheers

**Comment by adamralph** [comment]
@paulvanbladel great stuff. Please keep me in the loop with regard to the reporting solution. I'll be more than happy to do my bit to publicise it. Thanks for raising this discussion.
