### ISSUE TITLE
Switch to xUnit.net 2.0

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#51]
This is an opinionated subset of 1.0 features which I believe are required in version 2. If any features have been omitted, it is because I have never used them, nor have I heard of anybody using them, or I have only heard of them being used in an edge case. Ultimately the framework is designed to be extensible so if any edge cases are not being catered for then the extensibility points should be examined first before adding specific features.

This issue only tackles net45 support. Support for other platforms has been spun off into #220, #221, #222, #223 and #224.
- [x] Update to stable xunit 2.0 release
- [x] Features
  - [x] AsyncScenarioFeature
  - [x] AsyncStepFeature
  - [x] BackgroundFeature
  - [x] DefaultParametersFeature
  - [x] ExampleFeature
  - [x] ObjectDisposalFeature
    - [x] Remove teardown step and send `ITestCaseCleanupFailure` if required (2.0 change)
  - [x] ScenarioFeature
  - [x] SkippedScenarioFeature
  - [x] SkippedStepFeature
  - [x] TeardownFeature
    - [x] Remove teardown step and send `ITestCaseCleanupFailure` if required
- [x] xUnit.net 2.0 feature support
  - [x] BeforeAfterTestFeature - before after scenario instead of step
  - [x] ClassFixtureFeature
  - [x] CollectionFixtureFeature
  - [x] MemberDataFeature
  - [x] TestClassFeature (was designed as an xbehave 1.x feature but not tested and did not work)
  - [x] TraitsFeature
- [x] Build
  - [x] Build packages
- [x] Runner compatibility
  - [x] xunit.runner.console
  - [x] xunit.runner.visualstudio
  - [x] xunit.runner.msbuild
  - [x] TestDriven.net
  - [x] Resharper (thanks to @citizenmatt for debugging)
    - [x] extra 'aborted' test
    - [x] a skipped step leaves the entire scenario marked as 'inconclusive'
    - [x] a skipped scenario results in thousands of redundant nodes in the UI
  - [x] NCrunch
    - [x] scenarios are not discovered (successfully tested in debug build provided by @remcomulder)
    - [x] skipped steps cause scenario to show as failed (https://gist.github.com/adamralph/110fb590a14c8cda41ff) needs a new build of NCrunch which reports the tests as inconclusive, so that the user can configure whether to show them as failed (default) or passed

**Comment by giggio** [comment]
@adamralph Any idea of when this will be done?

**Comment by adamralph** [comment]
Progress is good. I've been working on the Teardown feature today. I'm
optimistic that I can push out a beta as Christmas present :smiley:

**Comment by giggio** [comment]
Nice! :+1:

**Comment by adamralph** [comment]
Teardown feature is done...

**Comment by adamralph** [comment]
ObjectDisposal done!

**Comment by adamralph** [comment]
BeforeAfterTestFeature done!

**Comment by giggio** [comment]
This is going fast! :raised_hands:

**Comment by adamralph** [comment]
:gift: Christmas has come early!

https://twitter.com/adamralph/status/542716213936521217

https://www.nuget.org/packages/Xbehave/2.0.0-beta001-build-488

**Comment by giggio** [comment]
Nice! :+1:

**Comment by adamralph** [comment]
Beta 2 is now on nuget, with added support for Windows 8.1+ (Universal), Windows Phone 8 (Silverlight) and Windows Phone 8.1+ (Universal)

https://www.nuget.org/packages/Xbehave/2.0.0-beta002-build494

**Comment by adamralph** [comment]
FYI: 2.0 beta 7 was released today - https://www.nuget.org/packages/Xbehave/2.0.0-beta007-build521

As you can see from the checklist, 2.0 is getting very close to RTM now. I'm waiting on some feedback from @remcomulder regarding NCrunch compatibility, but it could well be the case that beta 7 is fully functional and no longer requires any changes. Once we've managed to get NCrunch working, the road to RTM should be clear.

**Comment by adamralph** [comment]
Moved from source:

```C#
// TODO (adamralph): detach from TestInvoker, support BeforeAfterTest and return a RunSummary instead of a time
// TODO (adamralph): omit sending of class construction and disposal messages
// `TestClassConstructionStarting`, `TestClassConstructionFinished`, `TestClassDisposeStarting`, and `TestClassDisposeFinished`
    // TODO (adamralph): consider sending a test when there are no steps in a scenario
public class ScenarioTestInvoker : TestInvoker<IXunitTestCase>
```

**Comment by adamralph** [comment]
FYI: 2.0 beta 8 was released today - https://www.nuget.org/packages/Xbehave/2.0.0-beta008-build523

It turned out there was one subtle change required for NCrunch in the case when a scenario contains no steps (which is likely whilst it is being written).

The only remaining tasks for 2.0 are some minor internal refactorings. After these are done I will be releasing RC 1 for testing. The first RC to pass all the tests I can think of will become RTM.

**Comment by adamralph** [comment]
As discussed with @remcomulder, we need to attempt enumeration of tests at discovery time, with enumeration at execution time as a fall back only, as per xunit theories. NCrunch will be changed to deal with enumeration at execution time in the case of fall back, but other runners may not be so forgiving.

**Comment by adamralph** [comment]
LOL - I just realised something plainly obvious. test discovery at discovery time can never work for xbehave. When the scenario method is executed, the step delegates are collected and it is those that define the tests. I can't serialize those delegates :stuck_out_tongue_winking_eye:

It will have to stay as is, at execution time.

**Comment by adamralph** [comment]
RC1 is out now https://www.nuget.org/packages/Xbehave/2.0.0-rc001-build541

**Comment by ursenzler** [comment]
I think the xbehave package should have a dependency on xunit.core and not xunit. 
I don't want the xunit.assert to be added automatically.

**Comment by ursenzler** [comment]
When I update to RC 1, then I cannot find the `ContinueOnFailureAfter` class anymore.

The assembly is quite empty compared to the old version:

![image](https://cloud.githubusercontent.com/assets/287565/7160077/236369fa-e387-11e4-95d7-e7d39d29d718.png)

Where did the class go?

I use `_` for all steps, and I want to execute all assertion steps, even when an establish/given/setup step fails.

**Comment by adamralph** [comment]
@ursenzler the full set of 2.0 changes is listed at https://github.com/xbehave/xbehave.net/wiki/Changes-in-version-2.0. It is most certainly opinionated, which is why feedback like yours is very valuable, so thanks for that.

You are the first person  I've heard of, other than the original contributor, who uses `ContinueOnFailureAfter` :stuck_out_tongue_closed_eyes:. Personally, I've never used it and IMHO it doesn't have any value. Of the other BDD frameworks I've investigated, I'm yet to see one which offers this facility. I'm genuinely curious to know why you are using it. However, I think extensibility is the name of the game here. I'm reluctant to build in an edge case feature into the framework, but what if you had an extensibility point which allowed you to control the decision? Note that in xbehave 2.0, there really is no distinction between step types. Given, When, Then, And and But have disappeared completely and the strings really are just free text. But the extensibility hook could give you the name of the step which failed (and perhaps the names of all those that have been run so far) so that you can make a decision about whether to continue or not.

Which `_` are you using? Is it the undocumented one which I didn't even bother to put in the 2.0 changes page? :stuck_out_tongue: Can you give an example?

I concede that I have been quite heavy handed with breaking changes in 2.0, so it's good to be having this discussion.

**Comment by adamralph** [comment]
WRT the package dependency, I would really like to have `xbehave = xunit + {steps}` where `xunit = xunit.core + xunit.assert` (plus whatever else my be added in future).

We _could_ have `xbehave.core = xunit.core + {steps}` and `xbehave = xunit + xbehave.core`, but I'm not sure it's really worth it. Does having `xunit.assert` brought along cause any problems? It's no worse than 1.x, since xunit 1.x has assertions built into the same DLL. I'll have a think about it though, perhaps it won't be too much effort to split out a separate `xbehave.core`.

**Comment by ursenzler** [comment]
I used the ContinueOnFailureAfter so that when one assertion fails, all other are still run. 

But no big deal if they are now marked as not-run

If one fails, there is a problem anyway. 

I absolutely agree with keeping a library as small as possible.

**Comment by ursenzler** [comment]
No real problem with the xunit assertions. They are not extension methods and therefore don't pollute intellisense. If it is easier, keep it.

**Comment by adamralph** [comment]
The handling of failures is much nicer in 2.0. In 1.x, when a step in a scenario fails, the remaining steps are also marked as failures, with the message 'Failed to execute preceding step...'. In 2.0, the remaining steps are marked as _skipped_, with the _reason_ 'Failed to execute preceding...'. This eliminates a lot of noise in the test output and allows you to quickly home in on the actual steps that failed, as opposed to those that were simply skipped due to an earlier failure. I guess you may find less of a need for continuation after failure with that kind of output.

I'll keep thinking about the xbehave.core thing. The purist in me says that it ought to be done, but I'll have to take a quick look to see how much effort would be involved before offering more opinion.

**Comment by ursenzler** [comment]
I just liked the ContinueOnFailureAfter because it allowed steps to succeed even when one "assert" step failed. In the sense of the system could do this and that, but one thing failed. Now (depending on order), I don't know whether the remaining steps would have succeeded.
But for this to work, there needs to be some distinction between given, when and then. And I don't like that. So it probably is best  to keep the current, simple solution because there is no best solution.

Talking to the purist in you: if the result is a bunch of new packages, then this is not the solution. Then it's better to keep the reference to xunit.
I personally would like most that xbehave would just depend on xunit.core. Leaving the framework for assertions completely to the developer using xbehave. But as I said, I can live very well with the current dependency.

**Comment by adamralph** [comment]
I don't think there would be a bunch of new packages, it would just be one new package, xbehave.core.

For those that would normally install xunit, they can install xbehave and get the same xunit, with assertions.

For those that would normally install xunit.core, they can install xbehave.core and get the same xunit.core, without assertions.

The more I think about it, the more I think this should be done, to provide symmetry between xbehave and xunit. It _could_ come later, in >= 2.1, but if it's not too much effort then I'd be happy to roll it into 2.0.

**Comment by ursenzler** [comment]
:-)

**Comment by adamralph** [comment]
@ursenzler I've just pushed out RC2 which introduces the Xbehave.Core package https://www.nuget.org/packages/Xbehave.Core/2.0.0-rc002-build543

It would be great if you could give it a try.

**Comment by ursenzler** [comment]
I had a somewhat crary idea Regarding the handling of steps wit previously failed steps:
Try to run it, if it succeeds, mark it as succeeded, if it fails, mark it as inconclusive, because failure could be because of previous failed step. 
That would allow for execution and reporting of assertion steps (then, it) even when one of them fails. 
What do you think?

**Comment by ursenzler** [comment]
I checked xBehave.Core. Looks good.

**Comment by adamralph** [comment]
Great, thanks for trying it!

With regard to the crazy idea, unfortunately xunit does not have the concept of an inconclusive test result. The only possible results are Failed, Passed and Skipped.

What we could do is have new version of `ContinueOnFailureAfterAttribute` which takes a regex pattern in its constructor. Any step which matches the regex can trigger the behaviour. E.g. to continue after failure of any step beginning with "Then... " and subsequent steps, you would write

``` C#
[assembly: ContinueOnFailureAfter("^Then")]
```

**Comment by ursenzler** [comment]
That would work for me.

**Comment by adamralph** [comment]
OK, let's get that into RC3.

**Comment by ursenzler** [comment]
I migrated a lot of specs to xBehave 2.0. All works well, no problems found. Hope you get rid of the pre-release soon - so that my automatic scripts for updates work again :-)

**Comment by adamralph** [comment]
That's great! It certainly gives the RC a good vote of confidence.

**Comment by adamralph** [comment]
@ursenzler I've spent some good time agonising over the 'continue on failure' feature. What bothered me was that it's a highly specific extension and, especially, _one that I've never used_.

So I came up with a different idea. I've added a new step builder method, `ContinueOnFailure()` which can be used to indicate that a specific step should exhibit this behaviour, e.g.

``` C#
[Scenario]
public void Something()
{
    "Given something"
        .f(() => ...);

    "When something"
        .f(() => ...);

    "Then something"
        .f(() => ...)
        .ContinueOnFailure();

    "And something else"
        .f(() => ...);

    "And something else again"
        .f(() => ...);
}
```

In this scenario, if `"Then something"` fails then the remaining `"And..."` steps are still executed instead of being skipped. However, if `"And something else"` fails then `"And something else again"` is skipped, since the `ContinueOnFailure()` only applies to `"Then something"`.

This allows control of the behaviour at the most granular level possible, i.e. individual steps. This is a feature I think I might use :wink:.

Now, in order to allow people to emulate the behaviour of the 1.x `ContinueOnFailureAfterAttribute`, I propose to add a 2.x `StepDefinitionsFilterAttribute` (name not finalised) as an extensibility point, e.g.

``` C#
[Scenario]
[ContinueOnFailureAfterThen]
public void Something()
{
    "Given something"
        .f(() => ...);

    "When something"
        .f(() => ...);

    "Then something"
        .f(() => ...);

    "And something else"
        .f(() => ...);

    "And something else again"
        .f(() => ...);
}

// your own custom extension
public class ContinueOnFailureAfterThenAttribute : StepDefinitionsFilterAttribute
{
    public override void Filter(ICollection<IStepDefinition> steps)
    {
        foreach(var step in steps.SkipWhile(step => !step.Text.StartsWith("Then ")))
        {
            step.ContinueOnFailure = true;
        }
    }
}
```

Implementations  of 2.x `StepDefinitionsFilterAttribute` can be added at the method, class or assembly level, similarly to the 1.x `ContinueOnFailureAfterAttribute`.

Thoughts?

**Comment by ursenzler** [comment]
I like the idea with the attribute more. Mainly because I use "establish", "when", "it", "it" with no distinction between the assertion steps. The step builder method brings the concept of order to my assertion steps, which I don't like. What if I change the order?

The attribute would allow to run all "it" even if a single "it" fails. That's what I like.

**Comment by adamralph** [comment]
Which attribute are you referring to? There is the old 1.x attribute and the proposed new 2.x attribute.

**Comment by adamralph** [comment]
With 2.x attribute you can achieve what you want like so:

``` C#
[Scenario]
[ContinueOnFailureAfterIt]
public void Something()
{
    "Establish something"
        .f(() => ...);

    "When something"
        .f(() => ...);

    "It something"
        .f(() => ...);

    "It something else"
        .f(() => ...);

    "It something else again"
        .f(() => ...);
}

// your own custom extension
public class ContinueOnFailureAfterItAttribute: StepDefinitionsFilterAttribute
{
    public override void Filter(ICollection<IStepDefinition> steps)
    {
        foreach(var step in steps.SkipWhile(step => !step.Text.StartsWith("It ")))
        {
            step.ContinueOnFailure = true;
        }
    }
}
```

You don't need to use the step builder method at all. And you can freely change the order of your `It` steps.

**Comment by ursenzler** [comment]
I meant that the new proposed attribute solution is just perfect for my needs.
I won't need the step builder method.

**Comment by adamralph** [comment]
Ah, great! :smile:

OK, so that will be part of RC3 - tracked by https://github.com/xbehave/xbehave.net/issues/254

**Comment by adamralph** [comment]
https://www.nuget.org/packages/Xbehave/2.0.0

https://github.com/xbehave/xbehave.net/releases/tag/2.0.0
