### ISSUE TITLE
How to replace Example from XBehave with Autofixture's AutoMoqDataAttribute

### ISSUE THREAD

**Issue by farhad-taran** [adamralph/xbehave.net#561]
Hello,

I am trying to use an AutoMoqDataAttribute with my XBehave scenarios but it seems that when I do this I use the benefit of having different step information showing up on the Resharper or MsTest windows.

![Capture](https://user-images.githubusercontent.com/7329422/57209752-ae063080-6fd1-11e9-81f2-cf0004591779.PNG)

usually to provide data to your tests in Xbehave you use an Example attribute but I want to be able to provide already setup test data using autofixture.

I can see someone has had a similar issue [here](https://github.com/xbehave/xbehave.net/issues/285) and they have created this [gist](https://gist.github.com/iamkoch/81cecac9a3c5519a36801e01c8ab4968), but I am not sure how this will help or how it is supposed to be wired up to auto fixture.

here is my code:

```
[Scenario]
        [AutoMoqData]
        public void CorrelationId_WhenCorrelationIdIsPassedIn(
            string result,
            string correlationId,
            [Frozen(Matching.DirectBaseType)] DefaultHttpContext httpContext,
            [Frozen] Mock<IHttpContextAccessor> httpContextAccessorMock,
            CorrelationIdProvider sut)
        {
            $"Given a correlation id header value of {correlationId} has been passed in"
                .x(() =>
                {
                    httpContext.Request.Headers["x-Correlation-ID"] = correlationId;
                    httpContextAccessorMock.Setup(x => x.HttpContext).Returns(httpContext);
                });

            "When the correlation id is retrieved"
                .x(() => result = sut.CorrelationId);

            "Then the correlation id is not empty"
                .x(() => result.Should().NotBeEmpty());

            $"And the correlation id matches {correlationId}"
                .x(() => result.Should().Be(result));
        }
``` 
```
 public class AutoMoqDataAttribute : AutoDataAttribute
    {
        public AutoMoqDataAttribute() :
            base(() => new Fixture().Customize(new AutoMoqCustomization()))
        {
        }
    }
```

**Comment by adamralph** [comment]
Hi @ftaran, thanks for raising this. I'm not entirely sure I understand the problem. As long as the attribute you are using derives from xunit's `DataAttribute`, everything should just work.

**Comment by farhad-taran** [comment]
@adamralph
Is it possible to unseal the example attribute so that I can extend it? This way I will be able to automatically generate test data and get detailed info in the test window.

**Comment by adamralph** [comment]
@ftaran you can inherit directly from `Xunit.Sdk.DataAttribute`.

As you can see from the [source](https://github.com/xbehave/xbehave.net/blob/db8efe0ad055ec1c061f47af4d4e7b6747d66589/src/Xbehave.Core/ExampleAttribute.cs), `ExampleAttribute` is a trivial derivation of `DataAttribute`.

**Comment by iamkoch** [comment]
Ah hey. Yes, I wrote that Gist.

So I extended AutoData:

```
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public class CustomAutoDataAttribute : AutoDataAttribute
{
  public CustomAutoDataAttribute(params object[] data) : base(() => 
  {
    var fixture = new Fixture();

    fixture.Customize(new ExampleAutoDataSpecimenBuilder(data));
  }
}
```

with `ExampleAutoDataSpecimenBuilder` being from the above-mentioned gist. `ExampleAutoDataSpecimenBuilder` infers the parameter position in the target method then uses that to find the data by index in the `object[]` provided.

 You then adorn your scenarios with `[CustomAutoData(1, "two", 3)]` and it'll work how `Example` works

**Comment by adamralph** [comment]
@ftaran have you managed to acheive what you want?

**Comment by adamralph** [comment]
@ftaran I assume that, given the above info, you have enough to things working for you now. If not, please feel free to re-open this issue or raise another one.
