### ISSUE TITLE
Nested context/steps malfunction silently

### ISSUE THREAD

**Issue by skottmann** [adamralph/xbehave.net#595]
## Version(s)

2.4.0

## To reproduce

`"when1...".x(() => "when2...".x(() => throw new Exception("Test failure!")));`

## Expected behavior

As nested steps/contexts is an unsupported feature, `"when2...".x(()..)` should fail fast with an exception.

## Actual behaviour

No error happen. Test is green. 
Test failures and mistakes in writing tests are covered up by nesting of steps.
Diagnosis is cumbersome.

## Workarounds
Don't know any.

## Additional context
Support for nested steps, discussed in #98, is an alternate -better?!- solution. It's been open for 6 years now, however. As long as it's unresolved, it would make sense to limit the negative effects of this pitfall.

**Comment by BrunoJuchli** [comment]
This has been quite a pitfall for us when switching from another testing syntax.
Code reuse becomes limited, and we've got trade off's between having more finely grained test-entries (which make it easier to see what has failed) and clean code / maintainability of our tests.

Ideally of course we could write test code just like we write production code (same measures of clean, maintainability etc.).

**Comment by BrunoJuchli** [comment]
@adamralph 
I'm thinking about creating a PR for this. Does anything spring to mind which I should know?
No need to answer if it would take significant time, I'll probably be fine finding the way myself :-)

**Comment by adamralph** [comment]
@skottmann @BrunoJuchli thanks for raising this and for chiming in!

I agree that it would be better to throw an exception when a step is nested. That said, I'm not sure how easy this will be to fix. I'll have a think about it.

In the meantime, you are more than welcome to raise a PR. The PR branch should be based on `release-2.4.0`.

**Comment by adamralph** [comment]
@BrunoJuchli I'd prefer to call this an enhancement, rather than a bug. I.e. it was never the intention, nor was it ever documented, that nested step definition should throw an exception. It's a misuse of the API, and therefore those steps will never execute, but I think having an exception thrown is an improvement to behaviour rather than fixing incorrect behaviour. What do you think?

BTW - it will also need to be marked `breaking`, but I don't think it will actually break anyone.

**Comment by adamralph** [comment]
Replaced by #617, as a feature, not a bug.

**Comment by BrunoJuchli** [comment]
@adamralph
I think that's a completely valid view point. I believe there's other valid view points, but that It doesn't matter much as long as you stay consistent in xBehave.net. If you treated issues like that as enhancement before, I'd recommend continuing to do so.

Thanks a lot for you time / effort!
