### ISSUE TITLE
Throw an exception when steps are defined which will not be executed

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#617]
## Use case(s)

For example, if a step is defined in a nested context:

```c#
"Given something".x(() => "With something nested".x(() => { }));
```

The nested step will never be executed, and will effectively fail silently.

## Description

When a step is defined in a nested context, or in any other place where it will not be executed, such as outside a scenario or background method, an exception is thrown with the message:

> The currently executing thread is not in a step definition context

## Alternatives

An analyzer, but this would be quite tough to pull off and would add more packaging and deployment overhead, etc.

**Comment by adamralph** [comment]
Closed by https://github.com/xbehave/xbehave.net/pull/612.

**Comment by adamralph** [comment]
@BrunoJuchli I've released this enhancement in [2.4.1-rc.1](https://www.nuget.org/packages/Xbehave/2.4.1-rc.1). Would you mind giving it a try to check it works as expected?

**Comment by BrunoJuchli** [comment]
@adamralph I should get a chance to do so on Thursday. Will report back.

**Comment by BrunoJuchli** [comment]
@adamralph 
I've updated our code to use 2.4.1-rc.1. Existing tests work as before. When i try nesting, it works as expected.
![image](https://user-images.githubusercontent.com/2090172/66377881-b87a8b00-e9b2-11e9-94da-64d7ac8450ff.png)

I was wondering though whether it would be sensible to have a more comprehensive exception message to point the user in the right direction:

> The currently executing thread is not a step definition context. A common cause for this exception is step nesting - which is unsupported.

Notice, though, that English is not my mother-tongue.

**Comment by adamralph** [comment]
@BrunoJuchli that's not a bad idea. Since 2.4.1 has already gone into RC (I probably should have given you a beta first) I'll release RTM as-is, but I'll raise another issue to improve the exception message in 2.4.100.
