### ISSUE TITLE
Provide mechanisms allowing Background setup steps to be ordered

### ISSUE THREAD

**Issue by mwpowellhtx** [adamralph/xbehave.net#663]
## Use case(s)

I have some `Background` that are base class, followed by derived class.

## Description

I'd at least like for the base class steps to be handled in hierarchy order. Following that, potentially ordering them within each base class, by declaration order if possible, or by providing an `int Ordinal` of some sort.

## Alternatives

For now, I provided a set of "helper functions" that ensure background states, but it kind of defeats the purpose of doing the background itself in the first place.

## Additional context

I may consider submitting a PR if the *Reflection*, etc, isn't too messy. Will start with a fork clone and check it out.

**Comment by mwpowellhtx** [comment]
[`ScenarioInvoker`](https://github.com/xbehave/xbehave.net/blob/16ffb03e5c814c2130e82270e1a91dbfc8639863/src/Xbehave.Execution/ScenarioInvoker.cs) looks promising, specifically [`InvokeScenarioMethodAsync`](https://github.com/xbehave/xbehave.net/blob/16ffb03e5c814c2130e82270e1a91dbfc8639863/src/Xbehave.Execution/ScenarioInvoker.cs#L150), and as I suspected, no ordering there. I'll have a deeper look at it.

**Comment by adamralph** [comment]
Hi @mwpowellhtx, thanks for raising this.

> I'd at least like for the base class steps to be handled in hierarchy order.

I can see why this would be useful. It all depends what xunit's `GetMethods` does, as called on this line: https://github.com/xbehave/xbehave.net/blob/aef2b5d113838c72b70d01e449a7ab07b5e4aad3/src/Xbehave.Execution/ScenarioInvoker.cs#L159

Perhaps it already returns methods in the order you desire?

> Following that, potentially ordering them within each base class, by declaration order if possible, or by providing an `int Ordinal` of some sort.

I'm unsure about this part. I'm not sure it makes much sense to write two `Background` methods in the same class. After all, why not put all the steps into one `Background` method?

**Comment by mwpowellhtx** [comment]
@adamralph Ran into a non-trivial kerfuffle. I think it could be resolved by assuming at least `netstandard2.0`. Bits that I need in either `ITypeInfo` or the corresponding `Reflection` `MethodInfo` were not available in `netstandard1.1`. Any reason why xBehave should target anything less than `netstandard2.0`?

**Comment by mwpowellhtx** [comment]
@adamralph Oh, and to address your question, the order is not guaranteed to be in hierarchy order, from base class(es) on up the chain, which I would expect from something like a `Background` method. Added unit tests around that to begin the process, and found that out early.

**Comment by mwpowellhtx** [comment]
Okay, so `IMethodInfo.Type` is throwing `NotSupportedException`. I suspect that is probably deep within `xUnit` itself. So that's most likely a dead end. Otherwise, `IMethodInfo.Type` and `ITypeInfo.BaseType` might be a viable path to consider.

However, after raising the bar on `netstandard`, I was able to leverage `ToRuntimeMethod` and subsequently both `Type.DeclaringType` and `Type.BaseType`. That's what we need to even begin thinking about ordering `Background` methods according to hierarchy order.

Assuming that works, could also consider `Ordinal` ordering within the scope of each class pretty simply I should think.

**Comment by mwpowellhtx** [comment]
Upping to `netstandard2.0` also carries with it raising the desktop bar to `net472`, minimum, I think. I'll await a little feedback while I continue vetting the solution on my end. All that assuming my cleaning `obj` and `bin` directories and running `dotnet restore` yielded reliable results.

**Comment by mwpowellhtx** [comment]
```C#
private class MethodInfoComparer : IComparer<MethodInfo>
{
    // ...
}
```

This is a pretty simple way of doing it:

```C#
foreach (var backgroundMethod in this.scenario.TestCase.TestMethod.TestClass.Class
    .GetMethods(false)
    .Where(candidate => candidate.GetCustomAttributes(typeof(BackgroundAttribute)).Any())
    //// tried and failed, IMethodInfo.Type and/or ITypeInfo.BaseType unsupported.
    //.OrderBy(candidate => candidate, new IMethodInfoComparer())
    .Select(method => method.ToRuntimeMethod())
    .OrderBy(method => method, new MethodInfoComparer())
    )
{
    // ...
}
```

Which yielded correctly resolved `Background` invocation.

**Comment by mwpowellhtx** [comment]
I have this in a draft working clone/branch for the moment. I'll understand if you are hesitant to raise either `dotnet` or `desktop` bars. Or perhaps the target frameworks could be strategically expanded to include `netstandard2.0` and `net472` with a couple of preprocessing flags.

Thinking of alternatives, I suppose I could "simply" virtualize a `Background` support method, and override in derived classes, but then that defeats the purpose of there being `Background` methods in the first place.

**Comment by mwpowellhtx** [comment]
@adamralph I'm prepared to commit and present the PR. Open question for you, are you open to the `netstandard2.0` `net472` update? Gauging from the commit history some months and/or years ago, I'd say this is probably more contemporary with the current state of `dotnet` affairs, IMO, but, then again, I do not know in which contexts `Xbehave` might be used.

**Comment by adamralph** [comment]
hi @mwpowellhtx, for the 2.x range, I'd like to remain inline with xunit 2.x with respect to the target frameworks.

**Comment by mwpowellhtx** [comment]
@adamralph Hmm, well, that's unfortunate, since the proposed solution does not work without the upgrade.

For now I'll kludge my way around it, but if you should change your mind, I can be ready with a stashed solution.

**Comment by adamralph** [comment]
@mwpowellhtx are you sure there is no way of achieving this under the current TFM's? If not, I guess this may have to wait for xbehave 3.x, which will be based on xunit 3.x. AFAIK the TFM's in xunit 3.x are going to be relatively late versions.

**Comment by mwpowellhtx** [comment]
You can look it up for yourself. I just followed the bread crumbs for the not implemented and other exceptions to MSDN, available on which runtimes, etc.

**Comment by mwpowellhtx** [comment]
Closing this one for now.
