### ISSUE TITLE
Q: Clarify ContainItemsAssignableTo usage

### ISSUE THREAD

**Issue by mwpowellhtx** [adamralph/xbehave.net#664]
Hello, could you clarify `FluentAssertions` `ContainItemsAssignableTo` usage throughout the tests please?

I think they are asking *"are all the values meeting the criteria"*, but one could read them, *"do any of the values meet the criteria"*.

I just need to clarify that, please. Thanks...

**Comment by blairconrad** [comment]
@mwpowellhtx, that's probably more of a FluentAssertions question (sadly, I don't think they document the test well over there), but based on 
https://github.com/xbehave/xbehave.net/blob/ab20152d1962859f294886e7ff4eed2ae163b3e3/tests/Xbehave.Test/DefaultParametersFeature.cs#L22
it seems to be "all".

**Comment by mwpowellhtx** [comment]
@blairconrad Thanks, yes, that was my first impression, notwithstanding the ambiguous method naming convention.
