### ISSUE TITLE
Assembly-level setup/teardown

### ISSUE THREAD

**Issue by redoz** [adamralph/xbehave.net#731]
We're using xbehave to integration test our application, and we need a means of doing "before all" and "after all" type setups/teardowns. I found [Xunit.Extensions.AssemblyFixture](https://github.com/JDCain/Xunit.Extensions.AssemblyFixture) which seems to work, but doesn't support ```IAsyncLifetime``` so you only get ctor/dispose which isn't going to work great for us as we're async-everything.

So the question is if there is support for anything like this in xbehave currently (I didn't find anything, but I'm also very new to the internals of xunit so I'm not quite sure how it all works together). The best idea for a workaround I have now is to create two collections, ```GlobalSetupCollection``` and ```GlobalTeardownCollection``` and implement my own ```ITestCollectionOrderer``` to ensure one executes first and the other last, but I might still have to deal with synchronization issues because the xunit docs states that if I disable parallelization on a collection (as I would for those two) they would execute _after_ all the other collections and I'm not sure the ```ITestCollectionOrderer``` is able to override that behavior.

Any suggestions where to look? Does xbehave already have code that runs before/after "everything" or is that handled by xunit2?

**Comment by adamralph** [comment]
@redoz there is nothing in xbehave for this. As you suggest, this is something that, if feasible, should really be addressed in xunit, (either natively or via an extension), and then the required changes, if any, should be made to xbehave to ensure it also supports it.

**Comment by redoz** [comment]
@adamralph Yeah, I think I'm going to lift some code from the extension project and build something that does what I need. I don't want to go to deep because it feels like with xunit3 everything is changing anyway. Hopefully they'll add more control over these things. Thanks for the quick reply!

**Comment by adamralph** [comment]
@redoz it may be worth chiming in with this suggestion over in https://github.com/xunit/xunit
