### ISSUE TITLE
Question: Every step treated as a test

### ISSUE THREAD

**Issue by Eklange** [adamralph/xbehave.net#741]
Hello, 

I really like how xBehave show all steps in test explorer but the drawback is that every step is then counted as a test. It would be good if the test count would not include all steps but maybe that is not possible to get if we also want to see all steps in test explorer?

Using resharper all steps are visible in the tree hierarchy but for built in test explorer in Visual studio you have to select the test and see steps Test Detail Summary. Is their a way to see steps in hierarchy like how resharper is doing?

**Comment by adamralph** [comment]
Hi @Eklange, I'm afraid that's a limitation/design choice of the Visual Studio test explorer. The best I can suggest is that you raise a feature request with Microsoft, but I'm afraid I don't know the best place to do that.
